import assert from 'node:assert/strict';
import fs from 'node:fs';
import { dueToday, pendingScheduleDates } from '../server/familyFinance.js';
import { validateFinancialImage } from '../server/financialReceiptAi.js';

const image = { name: 'comprobante.jpg', dataUrl: 'data:image/jpeg;base64,YQ==' };
assert.equal(validateFinancialImage(image), image);
assert.throws(() => validateFinancialImage({ dataUrl: 'data:text/plain;base64,YQ==' }), /fotografía JPG/);

const weekly = { starts_on: '2026-08-01', frequency: 'weekly', pay_day: 5 };
assert.equal(dueToday(weekly, '2026-08-21'), true, 'viernes debe activar una mesada configurada para viernes');
assert.equal(dueToday(weekly, '2026-08-22'), false, 'sábado no debe activar una mesada configurada para viernes');
const sunday = { starts_on: '2026-08-23', frequency: 'weekly', pay_day: 7 };
assert.equal(dueToday(sunday, '2026-08-23'), true, 'domingo debe activar una mesada configurada para domingo');
assert.deepEqual(pendingScheduleDates(sunday, '2026-08-24'), ['2026-08-23'], 'el lunes debe recuperar el cargo dominical omitido');
assert.deepEqual(pendingScheduleDates(sunday, '2026-08-24'), ['2026-08-23'], 'la conciliación conserva la misma clave de fecha para ser idempotente');
const monthly = { starts_on: '2026-08-01', frequency: 'monthly', pay_day: 21 };
assert.equal(dueToday(monthly, '2026-08-21'), true);
assert.equal(dueToday(monthly, '2026-08-20'), false);

const api = fs.readFileSync(new URL('../api/index.js', import.meta.url), 'utf8');
assert.match(api, /family\/receipts\/extract/);
assert.match(api, /requireAppPermission\(req, 'family\.approve'\)/);
assert.match(api, /readFinancialAttachment/);
assert.match(api, /family\/accounts\/\$\{account\.id\}\/share|accountShare/);
assert.match(api, /method === 'GET' \|\| method === 'POST'/);
const familyServer = fs.readFileSync(new URL('../server/familyFinance.js', import.meta.url), 'utf8');
assert.match(familyServer, /input\.image \? await uploadFinancialImage/);
assert.match(familyServer, /familyAccessDb\('account_share'/);
assert.match(familyServer, /movement_voided/);
assert.match(familyServer, /allowance_updated/);
assert.match(familyServer, /allowance_ended/);

const migration = fs.readFileSync(new URL('../supabase/migrations/20260822023000_family_finance_workflows.sql', import.meta.url), 'utf8');
assert.match(migration, /family-finance-documents/);
assert.match(migration, /status='pending'/);
assert.match(migration, /username='\[SENSITIVE\]'/);
const currentAccountMigration = fs.readFileSync(new URL('../supabase/migrations/20260822120000_unify_family_current_accounts.sql', import.meta.url), 'utf8');
assert.match(currentAccountMigration, /allowance_obligation_id/);
assert.match(currentAccountMigration, /allowance_charge/);
assert.match(currentAccountMigration, /on conflict\(allowance_obligation_id\)[\s\S]*where allowance_obligation_id is not null do nothing/);
assert.match(currentAccountMigration, /Cuenta corriente familiar/);
const allowanceSafetyMigration = fs.readFileSync(new URL('../supabase/migrations/20260822121000_pause_invalid_self_allowances.sql', import.meta.url), 'utf8');
assert.match(allowanceSafetyMigration, /beneficiary_user_id=responsible_user_id/);
assert.match(allowanceSafetyMigration, /status='paused'/);
const sharingMigration = fs.readFileSync(new URL('../supabase/migrations/20260822133000_family_accounts_and_external_loans.sql', import.meta.url), 'utf8');
assert.match(sharingMigration, /expense_account_members/);
assert.match(sharingMigration, /lender_external_name/);
assert.match(sharingMigration, /family_loans_parties_check/);
const mutationsMigration = fs.readFileSync(new URL('../supabase/migrations/20260823021500_family_recurring_and_movement_void.sql', import.meta.url), 'utf8');
assert.match(mutationsMigration, /allowance_update/);
assert.match(mutationsMigration, /allowance_end/);
assert.match(mutationsMigration, /movement_void/);
assert.doesNotMatch(mutationsMigration, /delete\s+from\s+public\.(allowances|expense_movements)/i);
const familyUi = fs.readFileSync(new URL('../src/components/FamilyFinancePage.tsx', import.meta.url), 'utf8');
assert.match(familyUi, /Mi cuenta corriente familiar/);
assert.match(familyUi, /Mis préstamos familiares/);
assert.doesNotMatch(familyUi, />Rendiciones</);
assert.doesNotMatch(familyUi, /EChart/);
assert.match(familyUi, /Agregar foto \(opcional\)/);
assert.match(familyUi, /Se carga únicamente en la fecha programada/);
assert.match(familyUi, /Editar gasto recurrente/);
assert.match(familyUi, /Movimiento eliminado y contraparte notificada/);
assert.match(familyUi, /kind:'income'\|'expense'/);
assert.match(familyUi, /Saldo inicial · 1 ene\./);
assert.match(familyUi, /bank-statement-head/);
assert.match(familyUi, /Gasto recurrente/);
assert.match(familyUi, /Los préstamos pendientes continúan en el año siguiente/);
assert.match(familyUi, /CheckCircle2/);
const familyAdminMigration = fs.readFileSync(new URL('../supabase/migrations/20260823143000_family_admin_movement_update.sql', import.meta.url), 'utf8');
assert.match(familyAdminMigration, /misolar_family_movement_update_backend/);
assert.doesNotMatch(familyAdminMigration, /role_permissions|expense_accounts/);
assert.doesNotMatch(familyAdminMigration, /delete\s+from\s+public\.expense_movements/i);
assert.match(familyUi, /Trabajar con usuario/);
assert.match(familyUi, /Movimiento actualizado, auditado y contraparte notificada/);
const appUi = fs.readFileSync(new URL('../src/App.tsx', import.meta.url), 'utf8');
assert.match(appUi, /solarChrome=page!==\'family\'&&page!==\'users\'&&page!==\'water\'/);
assert.match(appUi, /page===\'water\'.*El Arrayán/);
const vercel = fs.readFileSync(new URL('../vercel.json', import.meta.url), 'utf8');
assert.match(vercel, /family\/generate-allowances/);
assert.match(vercel, /5 4 \* \* \*/);
console.log('family finance workflow tests: ok');
