import { useEffect, useMemo, useState } from 'react';
import { Battery, Boxes, Cpu, Pencil, Plus, RadioTower, Save, Sun, Trash2, X } from 'lucide-react';
import { api } from '../services/api';
import type { DailyEnergy, Realtime } from '../types';
import { APP_VERSION, REFRESH_POLICY } from '../config';
import { batterySoc, batteryVoltage, effectiveGridPower, gridFrequency, gridVoltage, inverterTemperature, outputFrequency, outputVoltage, pvPower, technicalCatalog, watts } from '../utils/energy';

type Category='panel'|'battery'|'inverter'|'generator'|'other';
type ExtraSpecs={technology:string;nominalVoltage:string;nominalCurrent:string;maximumVoltage:string;connection:string;serialNumber:string;warranty:string};
type Asset={id?:number;category:Category;brand:string;model:string;quantity:number;unitPowerW:number|null;capacityKwh:number|null;installedAt:string;notes:string;extraSpecs:ExtraSpecs};
const EMPTY_SPECS:ExtraSpecs={technology:'',nominalVoltage:'',nominalCurrent:'',maximumVoltage:'',connection:'',serialNumber:'',warranty:''};
const EMPTY:Asset={category:'panel',brand:'',model:'',quantity:1,unitPowerW:null,capacityKwh:null,installedAt:'',notes:'',extraSpecs:{...EMPTY_SPECS}};
const CATEGORY:{[K in Category]:{label:string;icon:typeof Sun}}={panel:{label:'Paneles',icon:Sun},battery:{label:'Baterías',icon:Battery},inverter:{label:'Inversor',icon:Cpu},generator:{label:'Generador',icon:RadioTower},other:{label:'Otro equipo',icon:Boxes}};
const SPEC_LABELS:Record<keyof ExtraSpecs,string>={technology:'Tipo / tecnología',nominalVoltage:'Voltaje nominal',nominalCurrent:'Corriente nominal',maximumVoltage:'Voltaje máximo',connection:'Conexión',serialNumber:'N.º de serie',warranty:'Garantía'};
const normalize=(row:any):Asset=>({id:Number(row.id),category:row.category,brand:row.brand||'',model:row.model||'',quantity:Number(row.quantity||1),unitPowerW:row.unit_power_w==null?null:Number(row.unit_power_w),capacityKwh:row.capacity_kwh==null?null:Number(row.capacity_kwh),installedAt:row.installed_at||'',notes:row.notes||'',extraSpecs:{...EMPTY_SPECS,...(row.extra_specs||{})}});

export default function EquipmentPage({deviceSn,siteLabel,realtime,summary,gridLabel,today,week,month,lastSectionUpdate,quality,solarModel}:{deviceSn:string;siteLabel:string;realtime:Realtime;summary:Realtime;gridLabel:string;today:DailyEnergy;week:DailyEnergy;month:DailyEnergy;lastSectionUpdate:Record<string,Date|null>;quality:unknown;solarModel:unknown}){
  const [assets,setAssets]=useState<Asset[]>([]);const [editing,setEditing]=useState<Asset|null>(null);const [saving,setSaving]=useState(false);const [message,setMessage]=useState('');
  const load=()=>api<{assets:any[]}>(`devices/${deviceSn}/equipment`).then(result=>setAssets((result.assets||[]).map(normalize)));
  useEffect(()=>{if(deviceSn)void load().catch(()=>setMessage('No se pudo cargar el registro de equipos.'))},[deviceSn]);
  const totals=useMemo(()=>({installedWp:assets.filter(a=>a.category==='panel').reduce((sum,a)=>sum+a.quantity*Number(a.unitPowerW||0),0),batteryKwh:assets.filter(a=>a.category==='battery').reduce((sum,a)=>sum+a.quantity*Number(a.capacityKwh||0),0)}),[assets]);
  const catalog=useMemo(()=>technicalCatalog(realtime,summary,gridLabel),[realtime,summary,gridLabel]);
  const used=useMemo(()=>new Set(catalog.flatMap(section=>section.items.map(item=>item.source).filter(Boolean)) as string[]),[catalog]);
  const rawUnknown=useMemo(()=>[...new Set([...Object.keys(summary),...Object.keys(realtime)])].filter(key=>!used.has(key)).sort(),[summary,realtime,used]);
  async function save(){if(!editing)return;setSaving(true);setMessage('');try{await api(`devices/${deviceSn}/equipment${editing.id?`/${editing.id}`:''}`,{method:editing.id?'PUT':'POST',body:JSON.stringify(editing)});await load();setEditing(null);setMessage('Ficha del equipo guardada en Mi Solar.')}catch(error){setMessage(error instanceof Error?error.message:'No fue posible guardar el equipo.')}finally{setSaving(false)}}
  async function remove(asset:Asset){if(!asset.id||!window.confirm(`¿Eliminar ${asset.model||CATEGORY[asset.category].label} del registro?`))return;await api(`devices/${deviceSn}/equipment/${asset.id}`,{method:'DELETE'});await load()}
  return <section className="equipment-page">
    <header className="page-heading"><div><small>Inventario técnico · {siteLabel}</small><h1>Equipos de la instalación</h1><p>Registro permanente de paneles, baterías, inversores y generadores, vinculado exclusivamente a esta instalación.</p></div><button className="primary-action" onClick={()=>setEditing({...EMPTY})}><Plus/> Agregar equipo</button></header>
    <section className="equipment-live-grid"><article className="panel"><small>Producción actual</small><strong>{watts(pvPower(realtime,1)+pvPower(realtime,2))}</strong><p>PV1 {watts(pvPower(realtime,1))} · PV2 {watts(pvPower(realtime,2))}</p></article><article className="panel"><small>Potencia instalada registrada</small><strong>{(totals.installedWp/1000).toLocaleString('es-CL',{maximumFractionDigits:2})} kWp</strong><p>{assets.filter(a=>a.category==='panel').reduce((sum,a)=>sum+a.quantity,0)} paneles registrados</p></article><article className="panel"><small>Capacidad de baterías</small><strong>{totals.batteryKwh.toLocaleString('es-CL',{maximumFractionDigits:2})} kWh</strong><p>Estado {batterySoc(realtime).toFixed(0)}% · {batteryVoltage(realtime).toFixed(1)} V</p></article><article className="panel"><small>{gridLabel}</small><strong>{watts(Math.abs(effectiveGridPower(realtime)))}</strong><p>{gridVoltage(realtime).toFixed(1)} V · {gridFrequency(realtime).toFixed(1)} Hz</p></article></section>
    {message&&<p className="equipment-message" role="status">{message}</p>}
    <section className="equipment-registry">{assets.map(asset=>{const meta=CATEGORY[asset.category];const Icon=meta.icon;const specs=Object.entries(asset.extraSpecs).filter(([,value])=>String(value||'').trim()) as [keyof ExtraSpecs,string][];return <article className="panel equipment-asset" key={asset.id}><header><span><Icon/></span><div><small>{meta.label}</small><h2>{[asset.brand,asset.model].filter(Boolean).join(' · ')||'Información por completar'}</h2></div></header><dl><div><dt>Cantidad</dt><dd>{asset.quantity}</dd></div>{asset.unitPowerW!=null&&<div><dt>Potencia por unidad</dt><dd>{asset.unitPowerW.toLocaleString('es-CL')} W</dd></div>}{asset.capacityKwh!=null&&<div><dt>Capacidad por unidad</dt><dd>{asset.capacityKwh.toLocaleString('es-CL')} kWh</dd></div>}{asset.installedAt&&<div><dt>Instalado</dt><dd>{asset.installedAt}</dd></div>}</dl>{specs.length>0&&<div className="equipment-spec-chips">{specs.map(([key,value])=><span key={key}><small>{SPEC_LABELS[key]}</small><b>{value}</b></span>)}</div>}{asset.notes&&<p>{asset.notes}</p>}<footer><button onClick={()=>setEditing({...asset,extraSpecs:{...asset.extraSpecs}})}><Pencil/> Editar</button><button className="danger" onClick={()=>void remove(asset)}><Trash2/> Eliminar</button></footer></article>})}</section>
    <section className="panel equipment-runtime"><h2>Lecturas técnicas actuales</h2><div><span>Modo del inversor <b>{String(summary.workMode||realtime.workMode||'—')}</b></span><span>Salida AC <b>{outputVoltage(realtime).toFixed(1)} V · {outputFrequency(realtime).toFixed(1)} Hz</b></span><span>Temperatura <b>{inverterTemperature(realtime).toFixed(1)} °C</b></span></div></section>
    <section className="equipment-technical-section" aria-labelledby="equipment-technical-title"><header><small>Diagnóstico integrado</small><h2 id="equipment-technical-title">Información técnica</h2><p>Parámetros, calidad de datos y auditoría de la instalación.</p></header><section className="technical-summary"><article className="panel"><small>Versión de la app</small><strong>v{APP_VERSION}</strong></article><article className="panel"><small>Política de actualización</small><strong>30 s · 5 min · 5 min · 5 min</strong><p>Tiempo real · día · semana · mes</p></article><article className="panel"><small>Datos catalogados</small><strong>{catalog.reduce((count,section)=>count+section.items.filter(item=>item.value!==null).length,0)}</strong></article><article className="panel"><small>Muestras hoy</small><strong>{today.samples}</strong></article><article className="panel"><small>Muestras mes</small><strong>{month.samples}</strong></article></section><section className="technical-grid">{catalog.map(section=><article className="panel technical-section" key={section.title}><h2>{section.title}</h2>{section.items.map(item=><div className="technical-row" key={item.key}><span>{item.label}</span><strong>{item.value===null?'—':`${typeof item.value==='number'?item.value.toLocaleString('es-CL',{maximumFractionDigits:2}):item.value}${item.unit?` ${item.unit}`:''}`}</strong><small>{item.source||'campo no disponible'}</small></div>)}</article>)}</section><section className="panel technical"><h2>Parámetros disponibles no usados en el dashboard</h2><p>Se conservan aquí para facilitar diagnósticos y futuras estadísticas.</p><div className="unknown-parameter-grid">{rawUnknown.map(key=><div className="unknown-parameter" key={key}><span>{key}</span><strong>{String((realtime as Record<string,unknown>)[key]??(summary as Record<string,unknown>)[key]??'—')}</strong></div>)}</div><details><summary>Auditoría completa en JSON</summary><pre>{JSON.stringify({version:APP_VERSION,architecture:'Vercel native · caché aislado por equipo',refreshPolicyMs:REFRESH_POLICY,lastSectionUpdate,realtime,summary,today,week,month,quality,solarModel},null,2)}</pre></details></section></section>
    {editing&&<div className="equipment-modal" role="dialog" aria-modal="true"><form className="panel" onSubmit={event=>{event.preventDefault();void save()}}><header><div><small>{editing.id?'Editar ficha':'Nuevo equipo'}</small><h2>Especificaciones</h2></div><button type="button" onClick={()=>setEditing(null)} aria-label="Cerrar"><X/></button></header><div className="equipment-form-grid"><label>Tipo<select value={editing.category} onChange={event=>setEditing({...editing,category:event.target.value as Category})}>{Object.entries(CATEGORY).map(([key,value])=><option key={key} value={key}>{value.label}</option>)}</select></label><label>Cantidad<input type="number" min="1" value={editing.quantity} onChange={event=>setEditing({...editing,quantity:Number(event.target.value)})}/></label><label>Marca<input value={editing.brand} onChange={event=>setEditing({...editing,brand:event.target.value})} placeholder="Ej. Pylontech"/></label><label>Modelo<input value={editing.model} onChange={event=>setEditing({...editing,model:event.target.value})} placeholder="Modelo exacto"/></label><label>Potencia por unidad (W)<input type="number" min="0" value={editing.unitPowerW??''} onChange={event=>setEditing({...editing,unitPowerW:event.target.value===''?null:Number(event.target.value)})}/></label><label>Capacidad por unidad (kWh)<input type="number" min="0" step="0.1" value={editing.capacityKwh??''} onChange={event=>setEditing({...editing,capacityKwh:event.target.value===''?null:Number(event.target.value)})}/></label><label>Fecha de instalación<input type="date" value={editing.installedAt} onChange={event=>setEditing({...editing,installedAt:event.target.value})}/></label><fieldset className="equipment-extra-fields full"><legend>Especificaciones extra</legend>{(Object.keys(SPEC_LABELS) as (keyof ExtraSpecs)[]).map(key=><label key={key}>{SPEC_LABELS[key]}<input value={editing.extraSpecs[key]} onChange={event=>setEditing({...editing,extraSpecs:{...editing.extraSpecs,[key]:event.target.value}})} placeholder={key==='nominalVoltage'?'Ej. 48 V':key==='connection'?'Ej. 3 en serie':''}/></label>)}</fieldset><label className="full">Notas<textarea value={editing.notes} onChange={event=>setEditing({...editing,notes:event.target.value})} placeholder="Orientación, ubicación o información pendiente"/></label></div><button className="primary-action" disabled={saving}><Save/>{saving?'Guardando…':'Guardar ficha'}</button></form></div>}
  </section>;
}
