import { useEffect,useMemo,useState } from 'react';
import { Banknote,CalendarClock,HandCoins,Plus,ReceiptText,RefreshCw } from 'lucide-react';
import { api } from '../services/api';

type Person={id:string;display_name:string;username:string};
type Obligation={id:number;due_on:string;amount_minor:number;paid_amount_minor:number;status:string};
type Allowance={id:number;beneficiary_user_id:string;responsible_user_id:string;amount_minor:number;currency:string;frequency:string;pay_day?:number;status:string;obligations:Obligation[]};
type Payment={id:number;amount_minor:number;payment_date:string;detail?:string};
type Loan={id:number;loan_number:number;lender_user_id:string;borrower_user_id:string;loan_date:string;original_amount_minor:number;paid_amount_minor:number;currency:string;detail:string;due_date?:string;status:string;payments:Payment[]};
type Movement={id:number;movement_number:number;movement_date:string;detail:string;income_minor:number;expense_minor:number;currency:string;status:string};
type ExpenseAccount={id:number;user_id:string;currency:string;movements:Movement[]};
type Dashboard={users:Person[];allowances:Allowance[];loans:Loan[];expenseAccounts:ExpenseAccount[];notifications:{id:number;title:string;body:string;created_at:string;read_at?:string}[];scope:{admin:boolean}};
const clp=(value:number)=>new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(value);
const person=(users:Person[],id:string)=>users.find(user=>user.id===id)?.display_name||'Usuario';

export default function FamilyFinancePage(){
  const [data,setData]=useState<Dashboard|null>(null),[tab,setTab]=useState<'allowances'|'expenses'|'loans'>('allowances'),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[form,setForm]=useState<'allowance'|'expense'|'loan'|null>(null);
  async function load(){setBusy(true);setMessage('');try{setData(await api<Dashboard>('family'))}catch(error){setMessage(error instanceof Error?error.message:'No fue posible cargar el módulo familiar.')}finally{setBusy(false)}}
  useEffect(()=>{void load()},[]);
  const totals=useMemo(()=>({allowances:data?.allowances.reduce((sum,item)=>sum+Number(item.amount_minor),0)||0,loans:data?.loans.reduce((sum,item)=>sum+Math.max(0,Number(item.original_amount_minor)-Number(item.paid_amount_minor)),0)||0,expenses:data?.expenseAccounts.flatMap(item=>item.movements).reduce((sum,item)=>sum+Number(item.expense_minor)-Number(item.income_minor),0)||0}),[data]);
  async function submitAllowance(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const value=Object.fromEntries(new FormData(event.currentTarget));await api('family/allowances',{method:'POST',body:JSON.stringify({beneficiaryUserId:value.beneficiary,responsibleUserId:value.responsible,amountMinor:Number(value.amount),currency:'CLP',frequency:value.frequency,payDay:Number(value.payDay),startsOn:value.startsOn,notes:value.notes})});setForm(null);await load()}
  async function submitExpense(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const value=Object.fromEntries(new FormData(event.currentTarget));await api('family/expenses',{method:'POST',body:JSON.stringify({accountId:Number(value.account),date:value.date,detail:value.detail,incomeMinor:value.kind==='income'?Number(value.amount):0,expenseMinor:value.kind==='expense'?Number(value.amount):0,status:'pending'})});setForm(null);await load()}
  async function submitLoan(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const value=Object.fromEntries(new FormData(event.currentTarget));await api('family/loans',{method:'POST',body:JSON.stringify({lenderUserId:value.lender,borrowerUserId:value.borrower,date:value.date,amountMinor:Number(value.amount),currency:'CLP',detail:value.detail,dueDate:value.dueDate||null})});setForm(null);await load()}
  async function pay(loan:Loan){const raw=window.prompt(`Monto del pago. Saldo actual: ${clp(loan.original_amount_minor-loan.paid_amount_minor)}`);if(!raw)return;const amount=Number(raw.replace(/\D/g,''));await api(`family/loans/${loan.id}/payments`,{method:'POST',body:JSON.stringify({amountMinor:amount,date:new Date().toISOString().slice(0,10),detail:'Pago registrado en MiSolar',idempotencyKey:crypto.randomUUID()})});await load()}
  return <section className="family-page"><header className="page-heading"><div><small>Cuenta corriente familiar</small><h1>Mesadas y gastos familiares</h1><p>Dinero en enteros, pagos parciales, comprobantes y auditoría sin eliminar movimientos definitivamente.</p></div><button className="refresh-button" onClick={load}><RefreshCw className={busy?'spin':''}/></button></header>{message&&<div className="data-warning-banner">{message}</div>}<section className="family-kpis"><article className="panel"><CalendarClock/><small>Mesadas configuradas</small><strong>{clp(totals.allowances)}</strong></article><article className="panel"><ReceiptText/><small>Saldo de rendiciones</small><strong>{clp(totals.expenses)}</strong></article><article className="panel"><HandCoins/><small>Préstamos pendientes</small><strong>{clp(totals.loans)}</strong></article></section><nav className="family-tabs"><button className={tab==='allowances'?'active':''} onClick={()=>setTab('allowances')}>Mesada</button><button className={tab==='expenses'?'active':''} onClick={()=>setTab('expenses')}>Rendición de gastos</button><button className={tab==='loans'?'active':''} onClick={()=>setTab('loans')}>Préstamos entre usuarios</button></nav>
    {tab==='allowances'&&<section><header className="family-section-heading"><h2>Mesadas</h2>{data?.scope.admin&&<button className="primary-action" onClick={()=>setForm('allowance')}><Plus/>Configurar</button>}</header>{form==='allowance'&&<form className="panel family-form" onSubmit={submitAllowance}><UserFields users={data?.users||[]} names={['beneficiary','responsible']}/><label>Monto CLP<input name="amount" type="number" min="0" required/></label><label>Frecuencia<select name="frequency"><option value="monthly">Mensual</option><option value="biweekly">Quincenal</option><option value="weekly">Semanal</option><option value="custom">Personalizada</option></select></label><label>Día de pago<input name="payDay" type="number" min="1" max="31"/></label><label>Fecha inicial<input name="startsOn" type="date" required/></label><label>Observaciones<input name="notes"/></label><button className="primary-action">Guardar mesada</button></form>}<div className="family-list">{data?.allowances.map(item=><article className="panel family-record" key={item.id}><header><div><small>{item.frequency} · {item.status}</small><h3>{person(data.users,item.beneficiary_user_id)}</h3></div><strong>{clp(item.amount_minor)}</strong></header><p>Responsable: {person(data.users,item.responsible_user_id)} · día {item.pay_day||'personalizado'}</p><details><summary>Obligaciones y pagos</summary>{item.obligations.map(row=><p key={row.id}>{row.due_on} · {clp(row.paid_amount_minor)} de {clp(row.amount_minor)} · {row.status}</p>)}</details></article>)}</div></section>}
    {tab==='expenses'&&<section><header className="family-section-heading"><h2>Rendición de gastos</h2><button className="primary-action" onClick={()=>setForm('expense')}><Plus/>Movimiento</button></header>{form==='expense'&&<form className="panel family-form" onSubmit={submitExpense}><label>Cuenta<select name="account">{data?.expenseAccounts.map(account=><option key={account.id} value={account.id}>{person(data.users,account.user_id)}</option>)}</select></label><label>Fecha<input name="date" type="date" required/></label><label>Tipo<select name="kind"><option value="expense">Gasto</option><option value="income">Ingreso</option></select></label><label>Monto CLP<input name="amount" type="number" min="1" required/></label><label>Detalle<input name="detail" required/></label><button className="primary-action">Enviar a validación</button></form>}<div className="family-list">{data?.expenseAccounts.flatMap(account=>account.movements.map(item=><article className="panel family-record" key={item.id}><header><div><small>Movimiento #{item.movement_number} · {item.status}</small><h3>{item.detail}</h3></div><strong>{item.expense_minor?`− ${clp(item.expense_minor)}`:`+ ${clp(item.income_minor)}`}</strong></header><p>{item.movement_date} · {person(data.users,account.user_id)}</p></article>))}</div></section>}
    {tab==='loans'&&<section><header className="family-section-heading"><h2>Préstamos entre usuarios</h2><button className="primary-action" onClick={()=>setForm('loan')}><Plus/>Nuevo préstamo</button></header>{form==='loan'&&<form className="panel family-form" onSubmit={submitLoan}><UserFields users={data?.users||[]} names={['lender','borrower']}/><label>Fecha<input name="date" type="date" required/></label><label>Monto CLP<input name="amount" type="number" min="1" required/></label><label>Vencimiento opcional<input name="dueDate" type="date"/></label><label>Detalle<input name="detail" required/></label><button className="primary-action">Registrar préstamo</button></form>}<div className="family-list">{data?.loans.map(loan=>{const balance=loan.original_amount_minor-loan.paid_amount_minor,percent=loan.original_amount_minor?loan.paid_amount_minor/loan.original_amount_minor*100:0;return <article className="panel family-record loan-record" key={loan.id}><header><div><small>Préstamo #{loan.loan_number} · {loan.status}</small><h3>{person(data.users,loan.lender_user_id)} → {person(data.users,loan.borrower_user_id)}</h3></div><strong>{clp(balance)}</strong></header><p>{loan.detail}</p><div className="loan-progress"><span style={{width:`${Math.min(100,percent)}%`}}/></div><div className="loan-summary"><span>Original {clp(loan.original_amount_minor)}</span><span>Pagado {clp(loan.paid_amount_minor)}</span><span>{percent.toFixed(1)}%</span></div><button className="register-payment" onClick={()=>pay(loan)}><Banknote/>REGISTRAR PAGO</button><details><summary>{loan.payments.length} pagos registrados</summary>{loan.payments.map(payment=><p key={payment.id}>{payment.payment_date} · {clp(payment.amount_minor)} · {payment.detail}</p>)}</details></article>})}</div></section>}
  </section>;
}

function UserFields({users,names}:{users:Person[];names:[string,string]}){return <>{names.map(name=><label key={name}>{name==='beneficiary'?'Beneficiario':name==='responsible'?'Responsable':name==='lender'?'Prestamista':'Deudor'}<select name={name}>{users.map(user=><option key={user.id} value={user.id}>{user.display_name}</option>)}</select></label>)}</>}
