import { useEffect,useState } from 'react';
import { KeyRound,RefreshCw,ShieldCheck,UserPlus,Users } from 'lucide-react';
import { api } from '../services/api';

type User={id:string;username:string;displayName:string;email?:string;phone?:string;active:boolean;mustChangePassword:boolean;createdAt:string;lastLoginAt?:string;role:string;roleName:string;sites:{site_id:number;name:string;can_control_isolar:boolean}[];menus:Record<string,boolean>;actions:Record<string,boolean>;devices:{id:string;label:string;lastSeenAt?:string}[]};
const menus=['home','charts','solar','costs','equipment','programming','integrations','technical','water','users','family'];
const actions=['solar.view','family.view','family.create','family.approve','users.manage','credentials.manage','isolar.write','audit.view'];

export default function UsersPage(){
  const [users,setUsers]=useState<User[]>([]),[currentUserId,setCurrentUserId]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[creating,setCreating]=useState(false);
  const [form,setForm]=useState({username:'',displayName:'',password:'',email:'',phone:'',role:'member',menus:Object.fromEntries(menus.map(key=>[key,key==='home'||key==='family'])),actions:{'family.view':true}});
  async function load(){setBusy(true);setMessage('');try{const [data,session]=await Promise.all([api<{users:User[]}>('admin/users'),api<{user?:{id:string}}>('app-auth/session')]);setUsers(data.users||[]);setCurrentUserId(session.user?.id||'')}catch(error){setMessage(error instanceof Error?error.message:'No fue posible cargar los usuarios.')}finally{setBusy(false)}}
  useEffect(()=>{void load()},[]);
  async function create(event:React.FormEvent){event.preventDefault();setBusy(true);try{await api('admin/users',{method:'POST',body:JSON.stringify(form)});setCreating(false);setForm(value=>({...value,username:'',displayName:'',password:'',email:'',phone:''}));await load();setMessage('Usuario creado. Al primer ingreso deberá reemplazar la contraseña temporal.')}catch(error){setMessage(error instanceof Error?error.message:'No fue posible crear el usuario.')}finally{setBusy(false)}}
  async function toggle(user:User){if(!window.confirm(`¿Confirmas ${user.active?'desactivar':'activar'} a ${user.displayName}?`))return;await api(`admin/users/${user.id}`,{method:'PATCH',body:JSON.stringify({active:!user.active})});await load()}
  async function reset(user:User){const password=window.prompt(`Nueva contraseña temporal para ${user.displayName} (exactamente 8 caracteres):`);if(!password)return;await api(`admin/users/${user.id}/reset-password`,{method:'POST',body:JSON.stringify({password})});setMessage('Contraseña reemplazada y sesiones revocadas.');await load()}
  async function revoke(user:User){if(!window.confirm(`¿Revocar todas las sesiones y dispositivos autorizados de ${user.displayName}?`))return;await api(`admin/users/${user.id}/revoke-sessions`,{method:'POST'});setMessage('Sesiones revocadas.');await load()}
  return <section className="users-page"><header className="page-heading"><div><small>Administración segura</small><h1>Usuarios</h1><p>Roles, instalaciones, menús, acciones y dispositivos autorizados se validan también en el backend.</p></div><div className="heading-actions"><button className="primary-action" onClick={()=>setCreating(value=>!value)}><UserPlus/>Crear usuario</button><button className="refresh-button" onClick={load}><RefreshCw className={busy?'spin':''}/></button></div></header>{message&&<div className="data-warning-banner">{message}</div>}
    {creating&&<form className="panel user-create-form" onSubmit={create}><h2>Nuevo usuario</h2><div className="user-fields"><label>Nombre<input value={form.displayName} onChange={event=>setForm(value=>({...value,displayName:event.target.value}))}/></label><label>Usuario<input autoComplete="off" value={form.username} onChange={event=>setForm(value=>({...value,username:event.target.value}))}/></label><label>Contraseña temporal<input type="password" autoComplete="new-password" value={form.password} onChange={event=>setForm(value=>({...value,password:event.target.value}))}/></label><label>Rol<select value={form.role} onChange={event=>setForm(value=>({...value,role:event.target.value}))}><option value="member">Miembro familiar</option><option value="admin">Administrador</option></select></label><label>Correo opcional<input type="email" value={form.email} onChange={event=>setForm(value=>({...value,email:event.target.value}))}/></label><label>Teléfono opcional<input value={form.phone} onChange={event=>setForm(value=>({...value,phone:event.target.value}))}/></label></div><h3>Menús visibles</h3><div className="permission-grid">{menus.map(key=><label key={key}><input type="checkbox" checked={Boolean(form.menus[key as keyof typeof form.menus])} onChange={event=>setForm(value=>({...value,menus:{...value.menus,[key]:event.target.checked}}))}/>{key}</label>)}</div><h3>Acciones permitidas</h3><div className="permission-grid">{actions.map(key=><label key={key}><input type="checkbox" checked={Boolean(form.actions[key as keyof typeof form.actions])} onChange={event=>setForm(value=>({...value,actions:{...value.actions,[key]:event.target.checked}}))}/>{key}</label>)}</div><button className="primary-action" disabled={busy}>Crear con contraseña cifrada</button></form>}
    <section className="user-list">{users.map(user=>{const current=user.id===currentUserId;const accidental=/^\[.*\]$/.test(user.username)||/sensitive/i.test(user.username);return <article className={`panel user-card ${accidental?'user-card-warning':''}`} key={user.id}><header><span><Users/><div><h2>{user.displayName} {current&&<em className="current-user-badge">Tú</em>}</h2><small>@{user.username} · {user.roleName}</small></div></span><b className={user.active?'active-user':'inactive-user'}>{user.active?'Activo':'Desactivado'}</b></header>{accidental&&<p className="user-origin-warning">Cuenta accidental creada por un marcador oculto del entorno. No representa una instalación ni un inversor. Puedes desactivarla después de confirmar que estás usando <b>@ecodjamb</b>.</p>}<div className="user-summary"><span><small>Creado</small>{new Date(user.createdAt).toLocaleDateString('es-CL')}</span><span><small>Último acceso</small>{user.lastLoginAt?new Date(user.lastLoginAt).toLocaleString('es-CL'):'Nunca'}</span><span><small>Sesiones autorizadas</small>{user.devices.length}</span><span><small>Instalaciones</small>{user.role==='superadmin'?'Todas por rol':user.sites.map(site=>site.name).join(', ')||'Sin asignar'}</span></div><details><summary>Permisos y sesiones autorizadas</summary><p>Menús: {Object.entries(user.menus).filter(([,allowed])=>allowed).map(([key])=>key).join(', ')||'por rol'}</p><p>Acciones: {Object.entries(user.actions).filter(([,allowed])=>allowed).map(([key])=>key).join(', ')||'por rol'}</p><p>Sesiones: {user.devices.map(device=>device.label).join(', ')||'ninguna'}</p></details><footer><button onClick={()=>reset(user)}><KeyRound/>Restablecer acceso</button><button onClick={()=>revoke(user)}><ShieldCheck/>Revocar sesiones</button><button onClick={()=>toggle(user)} disabled={current}>{user.active?'Desactivar':'Activar'}</button></footer></article>})}</section>
  </section>;
}
