alter table public.utility_bills
  add column if not exists reported_kwh numeric(14,2),
  add column if not exists issue_date date,
  add column if not exists due_date date,
  add column if not exists customer_number text,
  add column if not exists meter_number text,
  add column if not exists tariff_name text,
  add column if not exists invoice_number text,
  add column if not exists service_address text,
  add column if not exists fixed_charge_clp numeric(14,2),
  add column if not exists energy_charge_clp numeric(14,2),
  add column if not exists other_charges_clp numeric(14,2),
  add column if not exists taxes_clp numeric(14,2),
  add column if not exists source text not null default 'manual',
  add column if not exists ai_extraction jsonb not null default '{}'::jsonb,
  add column if not exists ai_confidence numeric(4,3),
  add column if not exists ai_model text;

alter table public.utility_bills
  alter column previous_reading drop not null,
  alter column current_reading drop not null;

alter table public.utility_bills drop constraint if exists utility_bills_current_reading_check;
alter table public.utility_bills add constraint utility_bills_current_reading_check check (
  (previous_reading is null and current_reading is null) or
  (previous_reading is not null and current_reading is not null and current_reading >= previous_reading)
);
alter table public.utility_bills drop constraint if exists utility_bills_reported_kwh_check;
alter table public.utility_bills add constraint utility_bills_reported_kwh_check check (reported_kwh is null or reported_kwh >= 0);
alter table public.utility_bills drop constraint if exists utility_bills_ai_confidence_check;
alter table public.utility_bills add constraint utility_bills_ai_confidence_check check (ai_confidence is null or ai_confidence between 0 and 1);
alter table public.utility_bills drop constraint if exists utility_bills_charge_values_check;
alter table public.utility_bills add constraint utility_bills_charge_values_check check (
  (fixed_charge_clp is null or fixed_charge_clp >= 0) and
  (energy_charge_clp is null or energy_charge_clp >= 0) and
  (other_charges_clp is null or other_charges_clp >= 0) and
  (taxes_clp is null or taxes_clp >= 0)
);

create table if not exists public.utility_bill_documents (
  id bigint generated by default as identity primary key,
  bill_id bigint not null references public.utility_bills(id) on delete cascade,
  page_number smallint not null check (page_number between 1 and 4),
  storage_path text not null,
  original_name text,
  mime_type text not null check (mime_type in ('image/jpeg','image/png','image/webp')),
  bytes integer not null check (bytes > 0 and bytes <= 1500000),
  sha256 text not null,
  created_at timestamptz not null default now(),
  unique (bill_id, page_number)
);

create index if not exists utility_bill_documents_bill_idx on public.utility_bill_documents (bill_id, page_number);
alter table public.utility_bill_documents enable row level security;
revoke all on public.utility_bill_documents from public, anon, authenticated;
grant select, insert, update on public.utility_bill_documents to anon;
grant usage, select on sequence public.utility_bill_documents_id_seq to anon;
drop policy if exists misolar_backend_utility_bill_documents_all on public.utility_bill_documents;
create policy misolar_backend_utility_bill_documents_all on public.utility_bill_documents
  for all to anon
  using ((select private.request_is_misolar()))
  with check ((select private.request_is_misolar()));

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('utility-bill-pages', 'utility-bill-pages', false, 1500000, array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set public = false, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists misolar_backend_bill_pages_select on storage.objects;
create policy misolar_backend_bill_pages_select on storage.objects for select to anon
  using (bucket_id = 'utility-bill-pages' and (select private.request_is_misolar()));
drop policy if exists misolar_backend_bill_pages_insert on storage.objects;
create policy misolar_backend_bill_pages_insert on storage.objects for insert to anon
  with check (bucket_id = 'utility-bill-pages' and (select private.request_is_misolar()));
drop policy if exists misolar_backend_bill_pages_update on storage.objects;
create policy misolar_backend_bill_pages_update on storage.objects for update to anon
  using (bucket_id = 'utility-bill-pages' and (select private.request_is_misolar()))
  with check (bucket_id = 'utility-bill-pages' and (select private.request_is_misolar()));

comment on table public.utility_bill_documents is 'Metadatos de las fotografías privadas que respaldan cada cuenta eléctrica.';
comment on column public.utility_bills.reported_kwh is 'Consumo facturado explícito, especialmente útil cuando las lecturas no aparecen en las fotografías.';
comment on column public.utility_bills.ai_extraction is 'Extracción estructurada de la cuenta mediante OpenAI, conservada para analítica y auditoría.';
