create table if not exists public.solar_forecast_locks (
  id bigint generated by default as identity primary key,
  site_id bigint not null references public.solar_sites(id) on delete cascade,
  forecast_date date not null,
  forecast_kwh numeric(10,2) not null check (forecast_kwh >= 0),
  radiation_kwh_m2 numeric(10,2) not null check (radiation_kwh_m2 >= 0),
  sample_days integer not null default 0 check (sample_days >= 0),
  slope numeric(12,3) not null,
  intercept numeric(12,3) not null,
  r_squared numeric(8,3) not null,
  locked_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (site_id, forecast_date)
);

alter table public.solar_forecast_locks enable row level security;
revoke all on public.solar_forecast_locks from public, anon, authenticated;
grant select, insert on public.solar_forecast_locks to anon;
grant usage, select on sequence public.solar_forecast_locks_id_seq to anon;

drop policy if exists misolar_backend_solar_forecast_locks_all on public.solar_forecast_locks;
create policy misolar_backend_solar_forecast_locks_all on public.solar_forecast_locks
  for all to anon
  using ((select private.request_is_misolar()))
  with check ((select private.request_is_misolar()));

comment on table public.solar_forecast_locks is
  'Proyección solar inmutable por instalación y fecha, fijada a las 21:50 de Chile del día anterior.';
