create extension if not exists pg_net;
create extension if not exists pg_cron with schema pg_catalog;

alter table public.automation_rules
  drop constraint if exists automation_rules_threshold_kwh_check;
alter table public.automation_rules
  add constraint automation_rules_threshold_kwh_check check (threshold_kwh between 0 and 60);

create table if not exists public.automation_credentials (
  id bigint generated by default as identity primary key,
  site_id bigint not null unique references public.solar_sites(id) on delete cascade,
  credentials_cipher text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  site_id bigint not null references public.solar_sites(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  created_at timestamptz not null default now(),
  last_success_at timestamptz,
  failure_count integer not null default 0 check (failure_count >= 0)
);

create index if not exists push_subscriptions_site_idx
  on public.push_subscriptions (site_id);

create table if not exists public.automation_executions (
  id bigint generated by default as identity primary key,
  site_id bigint not null references public.solar_sites(id) on delete cascade,
  forecast_date date not null,
  evaluated_at timestamptz not null default now(),
  forecast_kwh numeric(8,2),
  threshold_kwh numeric(8,2) not null,
  preset text not null check (preset in ('sunny','cloudy')),
  action text not null check (action in ('changed','unchanged','failed')),
  before_config jsonb not null default '{}'::jsonb,
  after_config jsonb not null default '{}'::jsonb,
  message text not null,
  notified boolean not null default false,
  unique (site_id, forecast_date)
);

create index if not exists automation_executions_evaluated_idx
  on public.automation_executions (evaluated_at desc);

alter table public.automation_credentials enable row level security;
alter table public.push_subscriptions enable row level security;
alter table public.automation_executions enable row level security;

revoke all on public.automation_credentials, public.push_subscriptions, public.automation_executions from public, anon, authenticated;
grant select, insert, update on public.automation_credentials to anon;
grant select, insert, update, delete on public.push_subscriptions to anon;
grant select, insert, update on public.automation_executions to anon;
grant usage, select on sequence public.automation_credentials_id_seq to anon;
grant usage, select on sequence public.automation_executions_id_seq to anon;

drop policy if exists misolar_backend_automation_credentials_all on public.automation_credentials;
create policy misolar_backend_automation_credentials_all on public.automation_credentials
  for all to anon using ((select private.request_is_misolar()))
  with check ((select private.request_is_misolar()));

drop policy if exists misolar_backend_push_subscriptions_all on public.push_subscriptions;
create policy misolar_backend_push_subscriptions_all on public.push_subscriptions
  for all to anon using ((select private.request_is_misolar()))
  with check ((select private.request_is_misolar()));

drop policy if exists misolar_backend_automation_executions_all on public.automation_executions;
create policy misolar_backend_automation_executions_all on public.automation_executions
  for all to anon using ((select private.request_is_misolar()))
  with check ((select private.request_is_misolar()));

comment on table public.automation_credentials is 'Credenciales i.Solar cifradas por el backend; la llave permanece exclusivamente en Vercel.';
comment on table public.push_subscriptions is 'Suscripciones Web Push por instalación para avisos de automatización.';
comment on table public.automation_executions is 'Resultado diario idempotente de la automatización solar.';

do $$
declare existing_job bigint;
begin
  select jobid into existing_job from cron.job where jobname = 'misolar-automation-every-5-minutes' limit 1;
  if existing_job is not null then perform cron.unschedule(existing_job); end if;
end $$;

select cron.schedule(
  'misolar-automation-every-5-minutes',
  '*/5 * * * *',
  $job$
  select net.http_post(
    url := 'https://misolar.vercel.app/api/automation/run',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'Authorization', 'Bearer ' || coalesce((select decrypted_secret from vault.decrypted_secrets where name = 'misolar_cron_secret' limit 1), '')
    ),
    body := jsonb_build_object('scheduled_at', now()),
    timeout_milliseconds := 55000
  ) as request_id;
  $job$
);
