create table if not exists public.utility_meter_readings (
  id bigint generated by default as identity primary key,
  site_id bigint not null references public.solar_sites(id) on delete cascade,
  period_start date not null,
  period_end date not null,
  opening_reading_kwh numeric(14,3) not null check (opening_reading_kwh >= 0),
  reading_at timestamptz not null,
  reading_kwh numeric(14,3) not null check (reading_kwh >= opening_reading_kwh),
  notes text,
  source text not null default 'manual' check (source in ('manual','bill')),
  created_at timestamptz not null default now(),
  check (period_end >= period_start)
);

create index if not exists utility_meter_readings_site_time_idx
  on public.utility_meter_readings (site_id, reading_at desc);
create index if not exists utility_meter_readings_site_period_idx
  on public.utility_meter_readings (site_id, period_start, period_end, reading_at desc);

alter table public.utility_meter_readings enable row level security;
revoke all on public.utility_meter_readings from public, anon, authenticated;
grant select, insert, delete on public.utility_meter_readings to anon;
grant usage, select on sequence public.utility_meter_readings_id_seq to anon;

drop policy if exists misolar_backend_utility_meter_readings_all on public.utility_meter_readings;
create policy misolar_backend_utility_meter_readings_all on public.utility_meter_readings
  for all to anon
  using ((select private.request_is_misolar()))
  with check ((select private.request_is_misolar()));

alter table public.water_settings
  add column if not exists notify_day_before boolean not null default true,
  add column if not exists notify_same_day boolean not null default true;

comment on table public.utility_meter_readings is
  'Lecturas manuales del medidor eléctrico para seguimiento y proyección del período Enel en curso.';
