-- Cuentas familiares compartidas y préstamos con participantes externos.
-- Migración aditiva: no elimina ni reescribe movimientos existentes.
create table if not exists public.expense_account_members (
  id bigint generated by default as identity primary key,
  account_id bigint not null references public.expense_accounts(id) on delete cascade,
  user_id uuid not null references public.app_users(id) on delete cascade,
  can_post boolean not null default true,
  added_by uuid references public.app_users(id) on delete set null,
  created_at timestamptz not null default now(),
  unique(account_id,user_id)
);
create index if not exists expense_account_members_user_idx
  on public.expense_account_members(user_id,account_id);
alter table public.expense_account_members enable row level security;
revoke all on public.expense_account_members from anon,authenticated;

alter table public.family_loans
  alter column lender_user_id drop not null,
  alter column borrower_user_id drop not null,
  add column if not exists lender_external_name text,
  add column if not exists borrower_external_name text;
alter table public.family_loans drop constraint if exists family_loans_check;
alter table public.family_loans add constraint family_loans_parties_check check (
  ((lender_user_id is not null)::int + (nullif(btrim(lender_external_name),'') is not null)::int)=1
  and ((borrower_user_id is not null)::int + (nullif(btrim(borrower_external_name),'') is not null)::int)=1
  and not (lender_user_id is not null and lender_user_id=borrower_user_id)
);

create or replace function public.misolar_family_access_backend(p_operation text,p_payload jsonb default '{}'::jsonb)
returns jsonb language plpgsql security definer set search_path='' as $$
declare
  v_result jsonb; v_id bigint; v_attachment uuid; v_extraction uuid;
begin
  if not (select private.request_is_misolar()) then raise exception 'backend no autorizado' using errcode='42501'; end if;
  case p_operation
    when 'dashboard' then
      select jsonb_build_object(
        'memberships',(select coalesce(jsonb_agg(to_jsonb(am) order by am.created_at),'[]'::jsonb)
          from public.expense_account_members am
          where (p_payload->>'admin')::boolean or am.user_id=(p_payload->>'user_id')::uuid),
        'accounts',(select coalesce(jsonb_agg(to_jsonb(ea)),'[]'::jsonb)
          from public.expense_accounts ea
          where ea.active=true and exists(select 1 from public.expense_account_members am where am.account_id=ea.id and am.user_id=(p_payload->>'user_id')::uuid)),
        'movements',(select coalesce(jsonb_agg(to_jsonb(em) order by em.movement_date desc,em.movement_number desc),'[]'::jsonb)
          from public.expense_movements em
          where exists(select 1 from public.expense_account_members am where am.account_id=em.account_id and am.user_id=(p_payload->>'user_id')::uuid)),
        'attachments',(select coalesce(jsonb_agg(jsonb_build_object('id',fa.id,'entity_type',fa.entity_type,'entity_id',fa.entity_id,'original_name',fa.original_name,'mime_type',fa.mime_type,'created_at',fa.created_at)),'[]'::jsonb)
          from public.financial_attachments fa
          where fa.entity_type='expense_movement' and exists(
            select 1 from public.expense_movements em join public.expense_account_members am on am.account_id=em.account_id
            where em.id=fa.entity_id::bigint and am.user_id=(p_payload->>'user_id')::uuid))
      ) into v_result;
    when 'access_check' then
      select jsonb_build_object('account_id',ea.id,'owner_user_id',ea.user_id,'currency',ea.currency,
        'member',exists(select 1 from public.expense_account_members am where am.account_id=ea.id and am.user_id=(p_payload->>'user_id')::uuid and am.can_post))
      into v_result from public.expense_accounts ea where ea.id=(p_payload->>'account_id')::bigint;
    when 'account_share' then
      insert into public.expense_account_members(account_id,user_id,can_post,added_by)
      values((p_payload->>'account_id')::bigint,(p_payload->>'user_id')::uuid,true,(p_payload->>'added_by')::uuid)
      on conflict(account_id,user_id) do update set can_post=true,added_by=excluded.added_by
      returning id into v_id;
      select to_jsonb(am) into v_result from public.expense_account_members am where am.id=v_id;
    when 'loan_create_external' then
      insert into public.family_loans(lender_user_id,borrower_user_id,lender_external_name,borrower_external_name,loan_date,original_amount_minor,currency,detail,due_date,created_by,approval_status)
      values(nullif(p_payload->>'lender_user_id','')::uuid,nullif(p_payload->>'borrower_user_id','')::uuid,
        nullif(btrim(p_payload->>'lender_external_name'),''),nullif(btrim(p_payload->>'borrower_external_name'),''),
        (p_payload->>'loan_date')::date,(p_payload->>'original_amount_minor')::bigint,coalesce(p_payload->>'currency','CLP'),
        p_payload->>'detail',nullif(p_payload->>'due_date','')::date,(p_payload->>'created_by')::uuid,'pending')
      returning id into v_id;
      if p_payload?'attachment' then
        insert into public.financial_attachments(owner_user_id,entity_type,entity_id,storage_path,original_name,mime_type,size_bytes,sha256,metadata)
        values((p_payload->>'created_by')::uuid,'family_loan',v_id::text,p_payload#>>'{attachment,storage_path}',p_payload#>>'{attachment,original_name}',p_payload#>>'{attachment,mime_type}',(p_payload#>>'{attachment,size_bytes}')::bigint,p_payload#>>'{attachment,sha256}',coalesce(p_payload#>'{attachment,metadata}','{}'::jsonb)) returning id into v_attachment;
        if p_payload?'ai_proposal' then
          insert into public.ai_document_extractions(attachment_id,proposed_values,model,status) values(v_attachment,p_payload->'ai_proposal',nullif(p_payload->>'ai_model',''),'validated') returning id into v_extraction;
          insert into public.financial_validations(extraction_id,validator_user_id,corrected_values) values(v_extraction,(p_payload->>'created_by')::uuid,coalesce(p_payload->'corrected_values','{}'::jsonb));
        end if;
      end if;
      select to_jsonb(l) into v_result from public.family_loans l where l.id=v_id;
    else raise exception 'operación no permitida' using errcode='22023';
  end case;
  return coalesce(v_result,'null'::jsonb);
end; $$;
revoke all on function public.misolar_family_access_backend(text,jsonb) from public,authenticated;
grant execute on function public.misolar_family_access_backend(text,jsonb) to anon;
