-- Fase 1 segura: integración multi-proveedor y telemetría canónica.
-- No toca los históricos existentes y no concede DELETE sobre telemetría.

create table if not exists public.inverters (
  id bigint generated by default as identity primary key,
  site_id bigint not null references public.solar_sites(id) on delete restrict,
  name text not null,
  model text,
  serial_masked text,
  active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.provider_accounts (
  id bigint generated by default as identity primary key,
  site_id bigint not null references public.solar_sites(id) on delete restrict,
  provider text not null check (provider in ('isolar','watchpower')),
  enabled boolean not null default false,
  username_masked text,
  credentials_cipher text,
  encryption_version smallint not null default 1,
  status text not null default 'not_configured' check (status in ('connected','disconnected','invalid_credentials','expired_session','temporarily_blocked','not_configured','unavailable')),
  consecutive_failures smallint not null default 0 check (consecutive_failures between 0 and 100),
  blocked_until timestamptz,
  last_success_at timestamptz,
  last_attempt_at timestamptz,
  last_error_code text,
  last_error_sanitized text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(site_id, provider)
);

create table if not exists public.provider_devices (
  id bigint generated by default as identity primary key,
  provider_account_id bigint not null references public.provider_accounts(id) on delete cascade,
  inverter_id bigint references public.inverters(id) on delete set null,
  provider_device_id text not null,
  device_identifier_cipher text,
  serial_masked text,
  logger_identifier_cipher text,
  logger_serial_masked text,
  plant_identifier text,
  alias text,
  model text,
  firmware_main text,
  firmware_secondary text,
  logger_firmware text,
  protocol_code integer,
  device_address integer,
  active boolean not null default true,
  last_reading_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(provider_account_id, provider_device_id)
);

create table if not exists public.provider_sessions (
  id bigint generated by default as identity primary key,
  provider_account_id bigint not null references public.provider_accounts(id) on delete cascade,
  session_cipher text not null,
  encryption_version smallint not null default 1,
  expires_at timestamptz,
  refreshed_at timestamptz,
  revoked_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.raw_provider_payloads (
  id bigint generated by default as identity primary key,
  site_id bigint not null references public.solar_sites(id) on delete restrict,
  provider_device_id bigint references public.provider_devices(id) on delete set null,
  provider text not null check (provider in ('isolar','watchpower')),
  payload_type text not null,
  provider_timestamp text,
  sampled_at timestamptz,
  received_at timestamptz not null default now(),
  sanitized_payload jsonb not null,
  payload_sha256 text not null,
  normalizer_version text not null,
  unique(provider, payload_sha256)
);

create table if not exists public.telemetry_samples (
  id bigint generated by default as identity primary key,
  site_id bigint not null references public.solar_sites(id) on delete restrict,
  inverter_id bigint references public.inverters(id) on delete set null,
  provider_device_id bigint references public.provider_devices(id) on delete set null,
  provider text not null check (provider in ('isolar','watchpower')),
  sample_type text not null default 'realtime',
  provider_sample_id text,
  provider_timestamp text,
  provider_timezone text,
  sampled_at timestamptz not null,
  sampled_at_local text,
  received_at timestamptz not null default now(),
  data_age_seconds integer,
  canonical jsonb not null default '{}'::jsonb,
  quality jsonb not null default '{}'::jsonb,
  raw_payload_id bigint references public.raw_provider_payloads(id) on delete set null,
  normalizer_version text not null,
  idempotency_key text not null unique
);

create table if not exists public.energy_counters (
  id bigint generated by default as identity primary key,
  site_id bigint not null references public.solar_sites(id) on delete restrict,
  inverter_id bigint references public.inverters(id) on delete set null,
  provider_device_id bigint references public.provider_devices(id) on delete set null,
  provider text not null check (provider in ('isolar','watchpower')),
  counter_date date not null,
  period_type text not null check (period_type in ('day','month','year','total')),
  counters jsonb not null default '{}'::jsonb,
  sampled_at timestamptz not null,
  received_at timestamptz not null default now(),
  idempotency_key text not null unique
);

create table if not exists public.alarms (
  id bigint generated by default as identity primary key,
  site_id bigint not null references public.solar_sites(id) on delete restrict,
  inverter_id bigint references public.inverters(id) on delete set null,
  provider_device_id bigint references public.provider_devices(id) on delete set null,
  provider text not null check (provider in ('isolar','watchpower')),
  provider_alarm_id text,
  code text,
  severity text,
  message text,
  started_at timestamptz not null,
  cleared_at timestamptz,
  raw_payload_id bigint references public.raw_provider_payloads(id) on delete set null,
  idempotency_key text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.device_settings (
  id bigint generated by default as identity primary key,
  site_id bigint not null references public.solar_sites(id) on delete restrict,
  inverter_id bigint references public.inverters(id) on delete set null,
  provider_device_id bigint references public.provider_devices(id) on delete set null,
  provider text not null check (provider in ('isolar','watchpower')),
  settings jsonb not null default '{}'::jsonb,
  read_only boolean not null default true,
  sampled_at timestamptz not null,
  created_at timestamptz not null default now()
);

create table if not exists public.variable_mappings (
  id bigint generated by default as identity primary key,
  provider text not null check (provider in ('isolar','watchpower')),
  original_name text not null,
  canonical_name text not null,
  original_unit text,
  normalized_unit text,
  scale numeric not null default 1,
  formula text,
  sign_convention text,
  update_frequency_seconds integer,
  inverter_models text[] not null default '{}',
  confidence text not null default 'pending' check (confidence in ('confirmed','high','medium','low','pending')),
  example_value text,
  observations text,
  normalizer_version text not null,
  unique(provider, original_name, canonical_name, normalizer_version)
);

create table if not exists public.sync_runs (
  id bigint generated by default as identity primary key,
  site_id bigint references public.solar_sites(id) on delete set null,
  provider_device_id bigint references public.provider_devices(id) on delete set null,
  provider text not null check (provider in ('isolar','watchpower')),
  sync_type text not null,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  status text not null default 'running' check (status in ('running','success','partial','failed','skipped')),
  samples_received integer not null default 0,
  samples_inserted integer not null default 0,
  duplicates integer not null default 0,
  error_code text,
  error_sanitized text,
  duration_ms integer,
  next_retry_at timestamptz
);

create table if not exists public.credential_audit_events (
  id bigint generated by default as identity primary key,
  site_id bigint references public.solar_sites(id) on delete set null,
  provider_account_id bigint references public.provider_accounts(id) on delete set null,
  actor_user_id uuid,
  action text not null,
  success boolean not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists provider_accounts_site_provider_idx on public.provider_accounts(site_id, provider);
create index if not exists provider_sessions_account_expiry_idx on public.provider_sessions(provider_account_id, expires_at desc);
create index if not exists telemetry_site_provider_sampled_idx on public.telemetry_samples(site_id, provider, sampled_at desc);
create index if not exists telemetry_inverter_sampled_idx on public.telemetry_samples(inverter_id, sampled_at desc);
create index if not exists telemetry_received_idx on public.telemetry_samples(received_at desc);
create index if not exists raw_provider_device_sampled_idx on public.raw_provider_payloads(provider_device_id, sampled_at desc);
create index if not exists alarms_site_provider_started_idx on public.alarms(site_id, provider, started_at desc);
create index if not exists sync_runs_provider_started_idx on public.sync_runs(provider, started_at desc);

insert into public.provider_accounts(site_id, provider, enabled, status)
select id, 'isolar', true, 'disconnected' from public.solar_sites on conflict (site_id, provider) do nothing;
insert into public.provider_accounts(site_id, provider, enabled, status)
select id, 'watchpower', (device_sn = '96342509120972'), 'not_configured' from public.solar_sites on conflict (site_id, provider) do nothing;

do $$
declare t text;
begin
  foreach t in array array['inverters','provider_accounts','provider_devices','provider_sessions','raw_provider_payloads','telemetry_samples','energy_counters','alarms','device_settings','variable_mappings','sync_runs','credential_audit_events'] loop
    execute format('alter table public.%I enable row level security',t);
    execute format('revoke all on public.%I from anon,authenticated',t);
  end loop;
end $$;

comment on table public.provider_accounts is 'Credenciales externas cifradas; nunca se devuelven al frontend.';
comment on table public.telemetry_samples is 'Telemetría canónica multi-proveedor con idempotencia y trazabilidad temporal.';
comment on table public.raw_provider_payloads is 'Payloads sanitizados para auditoría y reprocesamiento.';
