-- Identidad propia de MiSolar y finanzas familiares. Todo permanece cerrado a
-- PostgREST; el backend accede únicamente mediante RPCs enumerados y protegidos.

create table if not exists public.roles (
  id bigint generated by default as identity primary key,
  key text not null unique,
  name text not null,
  created_at timestamptz not null default now()
);
create table if not exists public.permissions (
  id bigint generated by default as identity primary key,
  key text not null unique,
  description text not null default ''
);
create table if not exists public.role_permissions (
  role_id bigint not null references public.roles(id) on delete cascade,
  permission_id bigint not null references public.permissions(id) on delete cascade,
  primary key(role_id,permission_id)
);
create table if not exists public.app_users (
  id uuid primary key default gen_random_uuid(),
  username text not null unique,
  display_name text not null,
  email text,
  phone text,
  password_hash text not null,
  role_id bigint not null references public.roles(id) on delete restrict,
  active boolean not null default true,
  must_change_password boolean not null default true,
  last_login_at timestamptz,
  password_changed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists app_users_username_lower_idx on public.app_users(lower(username));
create table if not exists public.user_menu_permissions (
  user_id uuid not null references public.app_users(id) on delete cascade,
  menu_key text not null,
  allowed boolean not null,
  primary key(user_id,menu_key)
);
create table if not exists public.user_action_permissions (
  user_id uuid not null references public.app_users(id) on delete cascade,
  action_key text not null,
  allowed boolean not null,
  primary key(user_id,action_key)
);
create table if not exists public.user_site_permissions (
  user_id uuid not null references public.app_users(id) on delete cascade,
  site_id bigint not null references public.solar_sites(id) on delete cascade,
  can_view boolean not null default true,
  can_control_isolar boolean not null default false,
  primary key(user_id,site_id)
);
create table if not exists public.authorized_devices (
  id uuid primary key,
  user_id uuid not null references public.app_users(id) on delete cascade,
  label text not null,
  user_agent_hash text not null,
  last_ip_hash text,
  last_seen_at timestamptz not null default now(),
  revoked_at timestamptz,
  created_at timestamptz not null default now()
);
create table if not exists public.user_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.app_users(id) on delete cascade,
  refresh_token_hash text not null unique,
  csrf_token_hash text not null,
  device_id uuid references public.authorized_devices(id) on delete set null,
  expires_at timestamptz not null,
  last_used_at timestamptz not null default now(),
  revoked_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists user_sessions_user_active_idx on public.user_sessions(user_id,expires_at desc) where revoked_at is null;
create table if not exists public.audit_events (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references public.app_users(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text,
  before_values jsonb,
  after_values jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.allowances (
  id bigint generated by default as identity primary key,
  beneficiary_user_id uuid not null references public.app_users(id) on delete restrict,
  responsible_user_id uuid not null references public.app_users(id) on delete restrict,
  amount_minor bigint not null check(amount_minor>=0),
  currency text not null default 'CLP',
  frequency text not null check(frequency in('weekly','biweekly','monthly','custom')),
  pay_day smallint,
  custom_interval_days smallint,
  starts_on date not null,
  ends_on date,
  status text not null default 'active' check(status in('active','paused','ended')),
  notes text,
  created_by uuid references public.app_users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.allowance_obligations (
  id bigint generated by default as identity primary key,
  allowance_id bigint not null references public.allowances(id) on delete restrict,
  due_on date not null,
  amount_minor bigint not null check(amount_minor>=0),
  paid_amount_minor bigint not null default 0 check(paid_amount_minor>=0),
  status text not null default 'pending' check(status in('pending','partial','paid','overdue','void')),
  idempotency_key text not null unique,
  created_at timestamptz not null default now()
);
create table if not exists public.allowance_payments (
  id bigint generated by default as identity primary key,
  obligation_id bigint not null references public.allowance_obligations(id) on delete restrict,
  amount_minor bigint not null check(amount_minor>0),
  paid_on date not null,
  detail text,
  status text not null default 'confirmed' check(status in('confirmed','void')),
  idempotency_key text not null unique,
  created_by uuid references public.app_users(id) on delete set null,
  created_at timestamptz not null default now()
);
create table if not exists public.expense_accounts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.app_users(id) on delete restrict,
  name text not null default 'Rendición de gastos',
  currency text not null default 'CLP',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique(user_id,currency)
);
create sequence if not exists public.expense_movement_number_seq;
create table if not exists public.expense_movements (
  id bigint generated by default as identity primary key,
  account_id bigint not null references public.expense_accounts(id) on delete restrict,
  movement_number bigint not null unique default nextval('public.expense_movement_number_seq'),
  movement_date date not null,
  detail text not null,
  income_minor bigint not null default 0 check(income_minor>=0),
  expense_minor bigint not null default 0 check(expense_minor>=0),
  currency text not null,
  status text not null default 'pending' check(status in('draft','pending','approved','rejected','corrected','void')),
  created_by uuid references public.app_users(id) on delete set null,
  approved_by uuid references public.app_users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check((income_minor>0 and expense_minor=0) or (expense_minor>0 and income_minor=0))
);
create sequence if not exists public.family_loan_number_seq;
create table if not exists public.family_loans (
  id bigint generated by default as identity primary key,
  loan_number bigint not null unique default nextval('public.family_loan_number_seq'),
  lender_user_id uuid not null references public.app_users(id) on delete restrict,
  borrower_user_id uuid not null references public.app_users(id) on delete restrict,
  loan_date date not null,
  original_amount_minor bigint not null check(original_amount_minor>0),
  paid_amount_minor bigint not null default 0 check(paid_amount_minor>=0),
  currency text not null default 'CLP',
  detail text not null,
  due_date date,
  status text not null default 'pending' check(status in('pending','partially_paid','paid','overdue','disputed','void')),
  created_by uuid references public.app_users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check(lender_user_id<>borrower_user_id)
);
create table if not exists public.loan_payments (
  id bigint generated by default as identity primary key,
  loan_id bigint not null references public.family_loans(id) on delete restrict,
  amount_minor bigint not null check(amount_minor>0),
  payment_date date not null,
  detail text,
  status text not null default 'confirmed' check(status in('confirmed','void')),
  idempotency_key text not null unique,
  created_by uuid references public.app_users(id) on delete set null,
  created_at timestamptz not null default now()
);
create table if not exists public.financial_attachments (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid not null references public.app_users(id) on delete restrict,
  entity_type text not null,
  entity_id text,
  storage_path text not null,
  original_name text,
  mime_type text not null,
  size_bytes bigint not null check(size_bytes>0),
  sha256 text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create table if not exists public.ai_document_extractions (
  id uuid primary key default gen_random_uuid(),
  attachment_id uuid not null references public.financial_attachments(id) on delete restrict,
  proposed_values jsonb not null,
  model text,
  status text not null default 'proposed' check(status in('proposed','validated','rejected')),
  created_at timestamptz not null default now()
);
create table if not exists public.financial_validations (
  id bigint generated by default as identity primary key,
  extraction_id uuid references public.ai_document_extractions(id) on delete restrict,
  validator_user_id uuid not null references public.app_users(id) on delete restrict,
  corrected_values jsonb not null,
  validated_at timestamptz not null default now()
);
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.app_users(id) on delete cascade,
  type text not null,
  title text not null,
  body text not null,
  entity_type text,
  entity_id text,
  read_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists notifications_user_created_idx on public.notifications(user_id,created_at desc);
create index if not exists loans_participants_idx on public.family_loans(lender_user_id,borrower_user_id,created_at desc);

insert into public.roles(key,name) values ('superadmin','Superadministrador'),('admin','Administrador'),('member','Miembro') on conflict(key) do update set name=excluded.name;
insert into public.permissions(key,description) values
 ('credentials.manage','Administrar credenciales externas'),('users.manage','Administrar usuarios'),
 ('family.view','Ver módulo familiar'),('family.create','Crear movimientos familiares'),
 ('family.approve','Aprobar y administrar movimientos'),('isolar.write','Modificar parámetros i.Solar')
on conflict(key) do update set description=excluded.description;
insert into public.role_permissions(role_id,permission_id)
select r.id,p.id from public.roles r cross join public.permissions p where r.key='superadmin'
on conflict do nothing;
insert into public.role_permissions(role_id,permission_id)
select r.id,p.id from public.roles r join public.permissions p on p.key in('family.view','family.create') where r.key='member'
on conflict do nothing;
insert into public.role_permissions(role_id,permission_id)
select r.id,p.id from public.roles r join public.permissions p on p.key in('family.view','family.create','family.approve','isolar.write') where r.key='admin'
on conflict do nothing;

do $$ declare t text; begin
  foreach t in array array['roles','permissions','role_permissions','app_users','user_menu_permissions','user_action_permissions','user_site_permissions','authorized_devices','user_sessions','audit_events','allowances','allowance_obligations','allowance_payments','expense_accounts','expense_movements','family_loans','loan_payments','financial_attachments','ai_document_extractions','financial_validations','notifications'] loop
    execute format('alter table public.%I enable row level security',t);
    execute format('revoke all on public.%I from anon,authenticated',t);
  end loop;
end $$;
revoke all on sequence public.expense_movement_number_seq, public.family_loan_number_seq from anon,authenticated;
