-- Equivalencias iniciales auditables. WatchPower queda en estado pending hasta
-- validar una muestra real de la cuenta; no se presentan campos adivinados.
insert into public.variable_mappings(provider,original_name,canonical_name,original_unit,normalized_unit,scale,formula,sign_convention,update_frequency_seconds,confidence,observations,normalizer_version) values
('isolar','gridVoltage','grid.voltage','V','V',1,null,null,30,'high','Campo observado en la integración existente','1.0.0'),
('isolar','gridCurrent','grid.current','A','A',1,null,null,30,'medium','Validar disponibilidad por modelo','1.0.0'),
('isolar','gridFrequency','grid.frequency','Hz','Hz',1,null,null,30,'high','Campo directo','1.0.0'),
('isolar','gridPowerInputActiveTotal','grid.power','W','W',1,null,'positivo=importación',30,'confirmed','Solo se usa como red activa cuando statusGrid=1','1.0.0'),
('isolar','pvInputPower1','pv.mppt1_power','W','W',1,null,'positivo=generación',30,'confirmed','PV1','1.0.0'),
('isolar','pvInputPower2','pv.mppt2_power','W','W',1,null,'positivo=generación',30,'confirmed','PV2 cuando existe','1.0.0'),
('isolar','batteryVoltage','battery.voltage','V','V',1,null,null,30,'high','Campo directo','1.0.0'),
('isolar','batteryCapacity','battery.soc','%','%',1,null,null,30,'confirmed','Estado de carga','1.0.0'),
('isolar','batteryChargingPower','battery.power','W','W',1,'discharge-charge','negativo=carga',30,'confirmed','Se combina con descarga','1.0.0'),
('isolar','batteryDischargingPower','battery.power','W','W',1,'discharge-charge','positivo=descarga',30,'confirmed','Se combina con carga','1.0.0'),
('isolar','acOutputActivePowerTotal','load.active_power','W','W',1,null,'positivo=consumo',30,'confirmed','Carga activa total','1.0.0'),
('isolar','acOutputApparentPowerTotal','load.apparent_power','VA','VA',1,null,'positivo=consumo',30,'high','Potencia aparente','1.0.0'),
('isolar','workMode','inverter.mode',null,null,1,null,null,30,'high','Estado instantáneo; no confundir con prioridad','1.0.0'),
('isolar','outputSourcePriority','inverter.output_priority',null,null,1,null,null,300,'high','Configuración SBU/SOL/Utility','1.0.0'),
('watchpower','bt_grid_voltage','grid.voltage','V','V',1,null,null,30,'pending','Pendiente de validar con muestra real','1.0.0'),
('watchpower','bt_grid_current','grid.current','A','A',1,null,null,30,'pending','Pendiente de validar con muestra real','1.0.0'),
('watchpower','bt_grid_frequency','grid.frequency','Hz','Hz',1,null,null,30,'pending','Pendiente de validar con muestra real','1.0.0'),
('watchpower','bt_grid_active_power','grid.power','W','W',1,null,'por validar',30,'pending','Convención de signo pendiente','1.0.0'),
('watchpower','bt_voltage_1','pv.mppt1_voltage','V','V',1,null,null,30,'pending','MPPT1','1.0.0'),
('watchpower','pv_input_current','pv.mppt1_current','A','A',1,null,null,30,'pending','MPPT1','1.0.0'),
('watchpower','bt_input_power','pv.mppt1_power','W','W',1,null,'positivo=generación',30,'pending','Si falta se deriva V×A','1.0.0'),
('watchpower','bt_voltage_2','pv.mppt2_voltage','V','V',1,null,null,30,'pending','MPPT2 si el equipo lo entrega','1.0.0'),
('watchpower','pv2_input_current','pv.mppt2_current','A','A',1,null,null,30,'pending','MPPT2 si el equipo lo entrega','1.0.0'),
('watchpower','bt_battery_voltage','battery.voltage','V','V',1,null,null,30,'pending','Campo directo','1.0.0'),
('watchpower','bt_battery_capacity','battery.soc','%','%',1,null,null,30,'pending','Estado de carga','1.0.0'),
('watchpower','bt_battery_charging_current','battery.charge_current','A','A',1,null,'positivo=carga',30,'pending','Potencia se deriva con voltaje','1.0.0'),
('watchpower','bt_battery_discharge_current','battery.discharge_current','A','A',1,null,'positivo=descarga',30,'pending','Potencia se deriva con voltaje','1.0.0'),
('watchpower','bt_load_active_power_sole','load.active_power','W','W',1,null,'positivo=consumo',30,'pending','Pendiente de muestra real','1.0.0'),
('watchpower','bt_ac_output_apparent_power','load.apparent_power','VA','VA',1,null,'positivo=consumo',30,'pending','Permite derivar reactiva si VA≥|W|','1.0.0'),
('watchpower','sy_work_mode','inverter.mode',null,null,1,null,null,30,'pending','Estado instantáneo; no prioridad','1.0.0'),
('watchpower','bse_output_source_priority','inverter.output_priority',null,null,1,null,null,300,'pending','Solo lectura','1.0.0')
on conflict(provider,original_name,canonical_name,normalizer_version) do update set original_unit=excluded.original_unit,normalized_unit=excluded.normalized_unit,scale=excluded.scale,formula=excluded.formula,sign_convention=excluded.sign_convention,update_frequency_seconds=excluded.update_frequency_seconds,confidence=excluded.confidence,observations=excluded.observations;
