create table if not exists public.utility_bills (
  id bigint generated by default as identity primary key,
  site_id bigint not null references public.solar_sites(id) on delete cascade,
  period_start date not null,
  period_end date not null,
  previous_reading numeric(14,2) not null check (previous_reading >= 0),
  current_reading numeric(14,2) not null check (current_reading >= previous_reading),
  billed_kwh numeric(14,2) generated always as (current_reading - previous_reading) stored,
  amount_clp numeric(14,2) not null check (amount_clp >= 0),
  theoretical_grid_kwh numeric(14,3) not null default 0 check (theoretical_grid_kwh >= 0),
  archive_coverage_pct numeric(5,1) not null default 0 check (archive_coverage_pct between 0 and 100),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (period_end >= period_start),
  unique (site_id, period_start, period_end)
);

create index if not exists utility_bills_site_period_idx
  on public.utility_bills (site_id, period_end desc);

alter table public.utility_bills enable row level security;
revoke all on public.utility_bills from public, anon, authenticated;
grant select, insert, update on public.utility_bills to anon;
grant usage, select on sequence public.utility_bills_id_seq to anon;

drop policy if exists misolar_backend_utility_bills_all on public.utility_bills;
create policy misolar_backend_utility_bills_all on public.utility_bills
  for all to anon
  using ((select private.request_is_misolar()))
  with check ((select private.request_is_misolar()));

comment on table public.utility_bills is
  'Resumen mensual de cuentas eléctricas y comparación con el consumo de red reconstruido por Mi Solar.';

comment on table public.solar_forecast_locks is
  'Proyección solar inmutable por instalación y fecha, fijada a las 21:30 de Chile del día anterior.';
