create table if not exists public.solar_forecast_revisions (
  id bigint generated by default as identity primary key,
  site_id bigint not null references public.solar_sites(id) on delete cascade,
  forecast_date date not null,
  forecast_kwh numeric(10,2) not null check (forecast_kwh >= 0),
  radiation_kwh_m2 numeric(10,2) not null check (radiation_kwh_m2 >= 0),
  observed_at timestamptz not null default now()
);

create index if not exists solar_forecast_revisions_site_date_observed_idx
  on public.solar_forecast_revisions (site_id, forecast_date, observed_at desc);

alter table public.solar_forecast_revisions enable row level security;
revoke all on public.solar_forecast_revisions from public, anon, authenticated;
grant select, insert on public.solar_forecast_revisions to anon;
grant usage, select on sequence public.solar_forecast_revisions_id_seq to anon;

drop policy if exists misolar_backend_solar_forecast_revisions_all on public.solar_forecast_revisions;
create policy misolar_backend_solar_forecast_revisions_all on public.solar_forecast_revisions
  for all to anon
  using ((select private.request_is_misolar()))
  with check ((select private.request_is_misolar()));

comment on table public.solar_forecast_revisions is
  'Revisiones meteorológicas informativas posteriores al corte oficial; nunca sustituyen la proyección bloqueada.';
