create extension if not exists pgcrypto;
create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table if not exists private.app_secrets (
  name text primary key,
  secret_hash text not null,
  created_at timestamptz not null default now()
);
revoke all on private.app_secrets from public, anon, authenticated;

create or replace function private.request_is_misolar()
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from private.app_secrets
    where name='misolar_backend'
      and secret_hash=encode(extensions.digest(coalesce(current_setting('request.headers',true)::json->>'x-misolar-key',''),'sha256'),'hex')
  );
$$;
revoke all on function private.request_is_misolar() from public;
grant usage on schema private to anon;
grant execute on function private.request_is_misolar() to anon;

create table if not exists public.solar_sites (
  id bigint generated by default as identity primary key,
  device_sn text not null unique check (device_sn ~ '^[0-9]{8,20}$'),
  name text not null,
  timezone text not null default 'America/Santiago',
  installed_wp integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.energy_samples (
  id bigint generated by default as identity primary key,
  site_id bigint not null references public.solar_sites(id) on delete cascade,
  sample_at timestamptz not null,
  solar_w numeric not null default 0,
  pv1_w numeric not null default 0,
  pv2_w numeric not null default 0,
  load_w numeric not null default 0,
  grid_w numeric not null default 0,
  grid_active boolean,
  battery_charge_w numeric not null default 0,
  battery_discharge_w numeric not null default 0,
  battery_soc numeric,
  source text not null default 'tumcapp',
  raw jsonb not null default '{}'::jsonb,
  ingested_at timestamptz not null default now(),
  unique(site_id,sample_at)
);

create index if not exists energy_samples_site_time_idx on public.energy_samples(site_id,sample_at desc);
create index if not exists energy_samples_time_brin_idx on public.energy_samples using brin(sample_at);
alter table public.solar_sites enable row level security;
alter table public.energy_samples enable row level security;
revoke all on public.solar_sites from anon,authenticated;
revoke all on public.energy_samples from anon,authenticated;
grant select,insert,update on public.solar_sites to anon;
grant select,insert,update on public.energy_samples to anon;
grant usage,select on all sequences in schema public to anon;

create policy misolar_backend_sites_select on public.solar_sites for select to anon using ((select private.request_is_misolar()));
create policy misolar_backend_sites_insert on public.solar_sites for insert to anon with check ((select private.request_is_misolar()));
create policy misolar_backend_sites_update on public.solar_sites for update to anon using ((select private.request_is_misolar())) with check ((select private.request_is_misolar()));
create policy misolar_backend_samples_select on public.energy_samples for select to anon using ((select private.request_is_misolar()));
create policy misolar_backend_samples_insert on public.energy_samples for insert to anon with check ((select private.request_is_misolar()));
create policy misolar_backend_samples_update on public.energy_samples for update to anon using ((select private.request_is_misolar())) with check ((select private.request_is_misolar()));

comment on table public.energy_samples is 'Respaldo permanente de telemetría Mi Solar; acceso exclusivo del backend.';

create or replace view public.energy_hourly with (security_invoker = true) as
select site_id,date_trunc('hour',sample_at) bucket_at,avg(solar_w)::numeric(12,2) solar_w,avg(load_w)::numeric(12,2) load_w,avg(grid_w)::numeric(12,2) grid_w,avg(battery_charge_w)::numeric(12,2) battery_charge_w,avg(battery_discharge_w)::numeric(12,2) battery_discharge_w,avg(battery_soc)::numeric(8,2) battery_soc,count(*)::integer samples
from public.energy_samples group by site_id,date_trunc('hour',sample_at);
create or replace view public.energy_daily with (security_invoker = true) as
select site_id,date_trunc('day',sample_at) bucket_at,avg(solar_w)::numeric(12,2) solar_w,avg(load_w)::numeric(12,2) load_w,avg(grid_w)::numeric(12,2) grid_w,avg(battery_charge_w)::numeric(12,2) battery_charge_w,avg(battery_discharge_w)::numeric(12,2) battery_discharge_w,avg(battery_soc)::numeric(8,2) battery_soc,count(*)::integer samples
from public.energy_samples group by site_id,date_trunc('day',sample_at);
revoke all on public.energy_hourly from public,anon,authenticated;
revoke all on public.energy_daily from public,anon,authenticated;
grant select on public.energy_hourly to anon;
grant select on public.energy_daily to anon;
