alter table public.automation_rules
  add column if not exists conditions jsonb not null default '[]'::jsonb,
  add constraint automation_rules_conditions_array_check
    check (jsonb_typeof(conditions) = 'array');

update public.automation_rules
set conditions = jsonb_build_array(
  jsonb_build_object(
    'id', 'cloudy-default', 'enabled', true, 'kind', 'lessThan',
    'minKwh', 0, 'maxKwh', threshold_kwh, 'preset', 'cloudy',
    'runAtLocal', to_char(run_at_local, 'HH24:MI'), 'dayOffset', -1
  ),
  jsonb_build_object(
    'id', 'sunny-default', 'enabled', true, 'kind', 'between',
    'minKwh', threshold_kwh, 'maxKwh', 60, 'preset', 'sunny',
    'runAtLocal', to_char(run_at_local, 'HH24:MI'), 'dayOffset', -1
  )
)
where conditions = '[]'::jsonb;

alter table public.automation_executions
  add column if not exists automation_condition_id text;

create table if not exists public.equipment_assets (
  id bigint generated by default as identity primary key,
  site_id bigint not null references public.solar_sites(id) on delete cascade,
  category text not null check (category in ('panel','battery','inverter','generator','other')),
  brand text not null default '',
  model text not null default '',
  quantity integer not null default 1 check (quantity between 1 and 10000),
  unit_power_w numeric(10,2) check (unit_power_w is null or unit_power_w >= 0),
  capacity_kwh numeric(10,2) check (capacity_kwh is null or capacity_kwh >= 0),
  installed_at date,
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists equipment_assets_site_category_idx
  on public.equipment_assets (site_id, category, created_at);

alter table public.equipment_assets enable row level security;
revoke all on public.equipment_assets from public, anon, authenticated;
grant select, insert, update, delete on public.equipment_assets to anon;
grant usage, select on sequence public.equipment_assets_id_seq to anon;

drop policy if exists misolar_backend_equipment_assets_all on public.equipment_assets;
create policy misolar_backend_equipment_assets_all on public.equipment_assets
  for all to anon
  using ((select private.request_is_misolar()))
  with check ((select private.request_is_misolar()));

insert into public.equipment_assets
  (site_id, category, brand, model, quantity, unit_power_w, capacity_kwh, notes)
select id, 'panel', '', 'Panel fotovoltaico 620 W', 14, 620, null,
  'Potencia instalada total: 8,68 kWp. Orientación norponiente.'
from public.solar_sites
where device_sn = '96342509120972'
  and not exists (select 1 from public.equipment_assets e where e.site_id = solar_sites.id and e.category = 'panel');

insert into public.equipment_assets
  (site_id, category, brand, model, quantity, unit_power_w, capacity_kwh, notes)
select id, 'battery', '', 'Batería 5 kWh', 2, null, 5,
  '10 kWh nominales; aproximadamente 9 kWh útiles.'
from public.solar_sites
where device_sn = '96342509120972'
  and not exists (select 1 from public.equipment_assets e where e.site_id = solar_sites.id and e.category = 'battery');

insert into public.equipment_assets
  (site_id, category, brand, model, quantity, unit_power_w, capacity_kwh, notes)
select id, 'inverter', '', 'Por completar', 1, null, null,
  'Completar marca, modelo y potencia nominal desde la ficha del equipo.'
from public.solar_sites
where device_sn = '96342509120972'
  and not exists (select 1 from public.equipment_assets e where e.site_id = solar_sites.id and e.category = 'inverter');

insert into public.equipment_assets
  (site_id, category, brand, model, quantity, unit_power_w, capacity_kwh, notes)
select id, 'panel', '', 'Panel fotovoltaico', 1, 1800, null,
  'Registro inicial: 1,8 kWp instalados. Separar por panel cuando se confirme cantidad y modelo.'
from public.solar_sites
where device_sn = '96322507118828'
  and not exists (select 1 from public.equipment_assets e where e.site_id = solar_sites.id and e.category = 'panel');

insert into public.equipment_assets
  (site_id, category, brand, model, quantity, unit_power_w, capacity_kwh, notes)
select id, 'inverter', '', 'Inversor off-grid · por completar', 1, null, null,
  'Instalación aislada; la entrada Grid corresponde al generador.'
from public.solar_sites
where device_sn = '96322507118828'
  and not exists (select 1 from public.equipment_assets e where e.site_id = solar_sites.id and e.category = 'inverter');

comment on column public.automation_rules.conditions is 'Reglas ordenadas por instalación: rango proyectado, perfil, hora local y día relativo de ejecución.';
comment on table public.equipment_assets is 'Inventario editable y persistente de paneles, baterías, inversores y generadores por instalación.';
