create table if not exists public.water_bills (
  id bigint generated by default as identity primary key,
  site_id bigint not null references public.solar_sites(id) on delete cascade,
  period_start date not null,
  period_end date not null,
  issue_date date,
  due_date date,
  next_reading_date date,
  previous_reading_m3 numeric(14,3),
  current_reading_m3 numeric(14,3),
  reading_difference_m3 numeric(14,3),
  deductible_m3 numeric(14,3),
  billed_m3 numeric(14,3) not null default 0,
  consumption_status text not null default 'estimated' check (consumption_status in ('actual','estimated','pending','unavailable')),
  estimate_method text,
  amount_clp numeric(14,2) not null default 0 check (amount_clp >= 0),
  customer_number text,
  meter_number text,
  meter_brand text,
  meter_model text,
  invoice_number text,
  service_address text,
  fixed_charge_clp numeric(14,2),
  potable_water_charge_clp numeric(14,2),
  sewer_collection_charge_clp numeric(14,2),
  wastewater_treatment_charge_clp numeric(14,2),
  subtotal_service_clp numeric(14,2),
  taxes_clp numeric(14,2),
  other_charges_clp numeric(14,2),
  discounts_clp numeric(14,2),
  charge_items jsonb not null default '[]'::jsonb,
  source text not null default 'manual',
  ai_extraction jsonb not null default '{}'::jsonb,
  ai_confidence numeric(4,3),
  ai_model text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (period_end >= period_start),
  check (previous_reading_m3 is null or previous_reading_m3 >= 0),
  check (current_reading_m3 is null or current_reading_m3 >= 0),
  check (reading_difference_m3 is null or reading_difference_m3 >= 0),
  check (deductible_m3 is null or deductible_m3 >= 0),
  check (billed_m3 >= 0),
  check (ai_confidence is null or ai_confidence between 0 and 1),
  unique (site_id, period_start, period_end)
);

create index if not exists water_bills_site_period_idx on public.water_bills (site_id, period_end desc);

create table if not exists public.water_bill_documents (
  id bigint generated by default as identity primary key,
  bill_id bigint not null references public.water_bills(id) on delete cascade,
  page_number smallint not null check (page_number between 1 and 4),
  storage_path text not null,
  original_name text,
  mime_type text not null check (mime_type in ('image/jpeg','image/png','image/webp')),
  bytes integer not null check (bytes > 0 and bytes <= 1500000),
  sha256 text not null,
  created_at timestamptz not null default now(),
  unique (bill_id, page_number)
);

create index if not exists water_bill_documents_bill_idx on public.water_bill_documents (bill_id, page_number);

create table if not exists public.water_meter_periods (
  id bigint generated by default as identity primary key,
  site_id bigint not null references public.solar_sites(id) on delete cascade,
  period_start date not null,
  expected_close_date date not null,
  actual_close_date date,
  opening_reading_m3 numeric(14,3) not null check (opening_reading_m3 >= 0),
  closing_reading_m3 numeric(14,3),
  status text not null default 'open' check (status in ('open','closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (expected_close_date >= period_start),
  check (actual_close_date is null or actual_close_date >= period_start),
  check (closing_reading_m3 is null or closing_reading_m3 >= opening_reading_m3)
);

create unique index if not exists water_meter_periods_one_open_idx on public.water_meter_periods (site_id) where status = 'open';
create index if not exists water_meter_periods_site_idx on public.water_meter_periods (site_id, period_start desc);

create table if not exists public.water_meter_readings (
  id bigint generated by default as identity primary key,
  site_id bigint not null references public.solar_sites(id) on delete cascade,
  period_id bigint references public.water_meter_periods(id) on delete set null,
  reading_at timestamptz not null,
  reading_m3 numeric(14,3) not null check (reading_m3 >= 0),
  source text not null default 'manual' check (source in ('manual','photo-ai','bill','closing')),
  notes text,
  storage_path text,
  original_name text,
  mime_type text check (mime_type is null or mime_type in ('image/jpeg','image/png','image/webp')),
  bytes integer check (bytes is null or (bytes > 0 and bytes <= 1500000)),
  sha256 text,
  ai_confidence numeric(4,3),
  ai_model text,
  ai_extraction jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  check (ai_confidence is null or ai_confidence between 0 and 1)
);

create index if not exists water_meter_readings_site_time_idx on public.water_meter_readings (site_id, reading_at desc);
create index if not exists water_meter_readings_period_idx on public.water_meter_readings (period_id, reading_at asc);

create table if not exists public.water_settings (
  site_id bigint primary key references public.solar_sites(id) on delete cascade,
  reminder_enabled boolean not null default true,
  reminder_days_before smallint not null default 2 check (reminder_days_before between 0 and 14),
  reminder_time_local time not null default '09:00',
  closing_day_hint smallint check (closing_day_hint between 1 and 31),
  updated_at timestamptz not null default now()
);

alter table public.water_bills enable row level security;
alter table public.water_bill_documents enable row level security;
alter table public.water_meter_periods enable row level security;
alter table public.water_meter_readings enable row level security;
alter table public.water_settings enable row level security;

revoke all on public.water_bills, public.water_bill_documents, public.water_meter_periods, public.water_meter_readings, public.water_settings from public, anon, authenticated;
grant select, insert, update, delete on public.water_bills, public.water_bill_documents, public.water_meter_periods, public.water_meter_readings, public.water_settings to anon;
grant usage, select on sequence public.water_bills_id_seq, public.water_bill_documents_id_seq, public.water_meter_periods_id_seq, public.water_meter_readings_id_seq to anon;

drop policy if exists misolar_backend_water_bills_all on public.water_bills;
create policy misolar_backend_water_bills_all on public.water_bills for all to anon using ((select private.request_is_misolar())) with check ((select private.request_is_misolar()));
drop policy if exists misolar_backend_water_bill_documents_all on public.water_bill_documents;
create policy misolar_backend_water_bill_documents_all on public.water_bill_documents for all to anon using ((select private.request_is_misolar())) with check ((select private.request_is_misolar()));
drop policy if exists misolar_backend_water_meter_periods_all on public.water_meter_periods;
create policy misolar_backend_water_meter_periods_all on public.water_meter_periods for all to anon using ((select private.request_is_misolar())) with check ((select private.request_is_misolar()));
drop policy if exists misolar_backend_water_meter_readings_all on public.water_meter_readings;
create policy misolar_backend_water_meter_readings_all on public.water_meter_readings for all to anon using ((select private.request_is_misolar())) with check ((select private.request_is_misolar()));
drop policy if exists misolar_backend_water_settings_all on public.water_settings;
create policy misolar_backend_water_settings_all on public.water_settings for all to anon using ((select private.request_is_misolar())) with check ((select private.request_is_misolar()));

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('water-cost-documents', 'water-cost-documents', false, 1500000, array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set public = false, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists misolar_backend_water_documents_select on storage.objects;
create policy misolar_backend_water_documents_select on storage.objects for select to anon using (bucket_id = 'water-cost-documents' and (select private.request_is_misolar()));
drop policy if exists misolar_backend_water_documents_insert on storage.objects;
create policy misolar_backend_water_documents_insert on storage.objects for insert to anon with check (bucket_id = 'water-cost-documents' and (select private.request_is_misolar()));
drop policy if exists misolar_backend_water_documents_update on storage.objects;
create policy misolar_backend_water_documents_update on storage.objects for update to anon using (bucket_id = 'water-cost-documents' and (select private.request_is_misolar())) with check (bucket_id = 'water-cost-documents' and (select private.request_is_misolar()));
drop policy if exists misolar_backend_water_documents_delete on storage.objects;
create policy misolar_backend_water_documents_delete on storage.objects for delete to anon using (bucket_id = 'water-cost-documents' and (select private.request_is_misolar()));

comment on table public.water_bills is 'Boletas de Aguas Andinas con consumo real o estimado, cargos desglosados y extracción IA auditable.';
comment on table public.water_meter_readings is 'Lecturas puntuales del medidor, manuales o extraídas de fotografías, para proyección del mes en curso.';
