alter table public.automation_rules
  add column if not exists notification_preferences jsonb not null default jsonb_build_object(
    'automationExecuted', true,
    'automationState', true,
    'serviceOutage', true,
    'solarSurplus', true
  );

create table if not exists public.notification_events (
  id bigint generated by default as identity primary key,
  site_id bigint not null references public.solar_sites(id) on delete cascade,
  event_type text not null check (event_type in ('automation_executed','automation_state','service_outage','service_recovery','solar_surplus','test')),
  title text not null,
  body text not null,
  dedupe_key text,
  delivered_count integer not null default 0 check (delivered_count >= 0),
  failed_count integer not null default 0 check (failed_count >= 0),
  created_at timestamptz not null default now()
);

create unique index if not exists notification_events_dedupe_idx
  on public.notification_events (site_id, dedupe_key)
  where dedupe_key is not null;
create index if not exists notification_events_site_created_idx
  on public.notification_events (site_id, created_at desc);

create table if not exists public.notification_states (
  site_id bigint not null references public.solar_sites(id) on delete cascade,
  event_key text not null,
  state text not null,
  metadata jsonb not null default '{}'::jsonb,
  last_notified_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key (site_id, event_key)
);

alter table public.notification_events enable row level security;
alter table public.notification_states enable row level security;

revoke all on public.notification_events, public.notification_states from public, anon, authenticated;
grant select, insert on public.notification_events to anon;
grant select, insert, update on public.notification_states to anon;
grant usage, select on sequence public.notification_events_id_seq to anon;

drop policy if exists misolar_backend_notification_events_all on public.notification_events;
create policy misolar_backend_notification_events_all on public.notification_events
  for all to anon
  using ((select private.request_is_misolar()))
  with check ((select private.request_is_misolar()));

drop policy if exists misolar_backend_notification_states_all on public.notification_states;
create policy misolar_backend_notification_states_all on public.notification_states
  for all to anon
  using ((select private.request_is_misolar()))
  with check ((select private.request_is_misolar()));

do $$
declare existing_job bigint;
begin
  select jobid into existing_job from cron.job where jobname = 'misolar-notification-monitor-every-5-minutes' limit 1;
  if existing_job is not null then perform cron.unschedule(existing_job); end if;
end $$;

select cron.schedule(
  'misolar-notification-monitor-every-5-minutes',
  '2-59/5 * * * *',
  $job$
  select net.http_post(
    url := 'https://misolar.vercel.app/api/notifications/monitor',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'Authorization', 'Bearer ' || coalesce((select decrypted_secret from vault.decrypted_secrets where name = 'misolar_cron_secret' limit 1), '')
    ),
    body := jsonb_build_object('scheduled_at', now()),
    timeout_milliseconds := 55000
  ) as request_id;
  $job$
);

comment on column public.automation_rules.notification_preferences is 'Preferencias de avisos push por instalación.';
comment on table public.notification_events is 'Auditoría permanente de avisos enviados por Mi Solar.';
comment on table public.notification_states is 'Estado persistente para detectar transiciones sin repetir avisos.';

-- Una instalación de la PWA representa al mismo propietario y recibe avisos de
-- todas sus casas. Replica las suscripciones existentes a cada sitio registrado.
insert into public.push_subscriptions (site_id, endpoint, p256dh, auth, failure_count)
select sites.id, subscriptions.endpoint, subscriptions.p256dh, subscriptions.auth, 0
from public.solar_sites sites
cross join (select distinct on (endpoint) endpoint, p256dh, auth from public.push_subscriptions order by endpoint, created_at desc) subscriptions
on conflict (site_id, endpoint) do update
set p256dh = excluded.p256dh, auth = excluded.auth, failure_count = 0;
