-- Horarios de domótica propios de Mi Solar. No altera los dispositivos ni borra reglas físicamente.
create table if not exists public.tuya_device_rules(
  id bigint generated by default as identity primary key,
  device_id text not null,
  device_name text not null,
  function_code text not null,
  start_time time not null,
  end_time time not null,
  days smallint[] not null default array[1,2,3,4,5,6,7]::smallint[],
  timezone text not null default 'America/Santiago',
  enabled boolean not null default true,
  conditions jsonb not null default '{}'::jsonb,
  created_by uuid references public.app_users(id) on delete set null,
  updated_by uuid references public.app_users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz,
  check(cardinality(days)>0 and days <@ array[1,2,3,4,5,6,7]::smallint[])
);
create index if not exists tuya_device_rules_active_idx on public.tuya_device_rules(device_id,enabled) where archived_at is null;

create table if not exists public.tuya_rule_runs(
  id bigint generated by default as identity primary key,
  rule_id bigint not null references public.tuya_device_rules(id) on delete restrict,
  run_key text not null unique,
  action text not null check(action in('start','end')),
  scheduled_for timestamptz not null,
  executed_at timestamptz,
  success boolean,
  error text,
  created_at timestamptz not null default now()
);
create index if not exists tuya_rule_runs_rule_idx on public.tuya_rule_runs(rule_id,created_at desc);
alter table public.tuya_device_rules enable row level security;
alter table public.tuya_rule_runs enable row level security;
revoke all on public.tuya_device_rules,public.tuya_rule_runs from anon,authenticated;

create or replace function public.misolar_tuya_rules_backend(p_operation text,p_payload jsonb default '{}'::jsonb)
returns jsonb language plpgsql security definer set search_path='' as $$
declare v_result jsonb;v_id bigint;
begin
  if not (select private.request_is_misolar()) then raise exception 'backend no autorizado' using errcode='42501'; end if;
  case p_operation
    when 'list' then
      select coalesce(jsonb_agg(to_jsonb(r) order by r.device_name,r.start_time),'[]'::jsonb) into v_result from public.tuya_device_rules r where archived_at is null;
    when 'enabled' then
      select coalesce(jsonb_agg(to_jsonb(r) order by r.id),'[]'::jsonb) into v_result from public.tuya_device_rules r where archived_at is null and enabled=true;
    when 'create' then
      insert into public.tuya_device_rules(device_id,device_name,function_code,start_time,end_time,days,timezone,enabled,conditions,created_by,updated_by)
      values(p_payload->>'device_id',p_payload->>'device_name',p_payload->>'function_code',(p_payload->>'start_time')::time,(p_payload->>'end_time')::time,array(select jsonb_array_elements_text(p_payload->'days')::smallint),coalesce(p_payload->>'timezone','America/Santiago'),coalesce((p_payload->>'enabled')::boolean,true),coalesce(p_payload->'conditions','{}'::jsonb),nullif(p_payload->>'created_by','')::uuid,nullif(p_payload->>'created_by','')::uuid)
      returning id into v_id;select to_jsonb(r) into v_result from public.tuya_device_rules r where id=v_id;
    when 'update' then
      update public.tuya_device_rules set device_id=p_payload->>'device_id',device_name=p_payload->>'device_name',function_code=p_payload->>'function_code',start_time=(p_payload->>'start_time')::time,end_time=(p_payload->>'end_time')::time,days=array(select jsonb_array_elements_text(p_payload->'days')::smallint),timezone=coalesce(p_payload->>'timezone','America/Santiago'),enabled=coalesce((p_payload->>'enabled')::boolean,true),conditions=coalesce(p_payload->'conditions','{}'::jsonb),updated_by=nullif(p_payload->>'updated_by','')::uuid,updated_at=now()
      where id=(p_payload->>'rule_id')::bigint and archived_at is null returning to_jsonb(public.tuya_device_rules.*) into v_result;
    when 'archive' then
      update public.tuya_device_rules set enabled=false,archived_at=now(),updated_by=nullif(p_payload->>'updated_by','')::uuid,updated_at=now() where id=(p_payload->>'rule_id')::bigint and archived_at is null returning to_jsonb(public.tuya_device_rules.*) into v_result;
    when 'claim' then
      insert into public.tuya_rule_runs(rule_id,run_key,action,scheduled_for) values((p_payload->>'rule_id')::bigint,p_payload->>'run_key',p_payload->>'action',(p_payload->>'scheduled_for')::timestamptz)
      on conflict(run_key) do nothing returning id into v_id;
      v_result:=case when v_id is null then jsonb_build_object('inserted',false) else jsonb_build_object('inserted',true,'id',v_id) end;
    when 'complete' then
      update public.tuya_rule_runs set executed_at=now(),success=(p_payload->>'success')::boolean,error=nullif(p_payload->>'error','') where id=(p_payload->>'run_id')::bigint returning to_jsonb(public.tuya_rule_runs.*) into v_result;
    else raise exception 'operación no permitida' using errcode='22023';
  end case;
  return coalesce(v_result,'null'::jsonb);
end; $$;
revoke all on function public.misolar_tuya_rules_backend(text,jsonb) from public,authenticated;
grant execute on function public.misolar_tuya_rules_backend(text,jsonb) to anon;
