alter table public.utility_bills
  add column if not exists misolar_projection jsonb not null default '{}'::jsonb,
  add column if not exists meter_projection jsonb not null default '{}'::jsonb,
  add column if not exists projection_snapshot_at timestamptz;

create table if not exists public.utility_projection_snapshots (
  id bigint generated by default as identity primary key,
  site_id bigint not null references public.solar_sites(id) on delete cascade,
  period_start date not null,
  period_end date not null,
  snapshot_date date not null,
  source text not null check (source in ('misolar','meter')),
  projected_kwh numeric(14,3) not null check (projected_kwh >= 0),
  projected_amount_clp numeric(14,2) not null check (projected_amount_clp >= 0),
  calculated_at timestamptz not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  check (period_end >= period_start),
  unique (site_id, period_start, period_end, snapshot_date, source)
);

create index if not exists utility_projection_snapshots_period_idx
  on public.utility_projection_snapshots (site_id, period_end desc, snapshot_date desc);

alter table public.utility_projection_snapshots enable row level security;
revoke all on public.utility_projection_snapshots from public, anon, authenticated;
grant select, insert, update on public.utility_projection_snapshots to anon;
grant usage, select on sequence public.utility_projection_snapshots_id_seq to anon;

drop policy if exists misolar_backend_utility_projection_snapshots_all on public.utility_projection_snapshots;
create policy misolar_backend_utility_projection_snapshots_all on public.utility_projection_snapshots
  for all to anon
  using ((select private.request_is_misolar()))
  with check ((select private.request_is_misolar()));

comment on table public.utility_projection_snapshots is
  'Cortes diarios de las proyecciones Mi Solar y por lecturas del medidor para comparar cada cuenta Enel con lo previsto.';
comment on column public.utility_bills.misolar_projection is
  'Última proyección Mi Solar congelada al ingresar la cuenta; no se recalcula al consultar el histórico.';
comment on column public.utility_bills.meter_projection is
  'Última proyección por lecturas reales congelada al ingresar la cuenta.';
