create table if not exists public.automation_rules (
  id bigint generated by default as identity primary key,
  site_id bigint not null unique references public.solar_sites(id) on delete cascade,
  enabled boolean not null default false,
  execution_mode text not null default 'manual' check (execution_mode in ('manual','automatic')),
  threshold_kwh numeric(8,2) not null default 20 check (threshold_kwh between 0 and 100),
  run_at_local time not null default '22:00',
  sunny_redischarge smallint not null default 25 check (sunny_redischarge between 10 and 100),
  sunny_output text not null default 'SBU' check (sunny_output in ('Utility','SOL','SBU')),
  cloudy_redischarge smallint not null default 50 check (cloudy_redischarge between 10 and 100),
  cloudy_output text not null default 'SOL' check (cloudy_output in ('Utility','SOL','SBU')),
  updated_at timestamptz not null default now()
);

create table if not exists public.inverter_configuration_events (
  id bigint generated by default as identity primary key,
  site_id bigint not null references public.solar_sites(id) on delete cascade,
  requested_at timestamptz not null default now(),
  source text not null check (source in ('manual','automatic','test')),
  preset text not null check (preset in ('sunny','cloudy')),
  forecast_date date,
  forecast_kwh numeric(8,2),
  before_config jsonb not null default '{}'::jsonb,
  target_config jsonb not null default '{}'::jsonb,
  after_config jsonb not null default '{}'::jsonb,
  commands jsonb not null default '{}'::jsonb,
  success boolean not null default false,
  message text not null default ''
);

create index if not exists inverter_configuration_events_site_requested_idx
  on public.inverter_configuration_events (site_id, requested_at desc);

alter table public.automation_rules enable row level security;
alter table public.inverter_configuration_events enable row level security;

grant select, insert, update on table public.automation_rules to anon;
grant select, insert on table public.inverter_configuration_events to anon;
grant usage, select on sequence public.automation_rules_id_seq to anon;
grant usage, select on sequence public.inverter_configuration_events_id_seq to anon;

drop policy if exists misolar_backend_automation_select on public.automation_rules;
create policy misolar_backend_automation_select on public.automation_rules for select to anon
using ((select private.request_is_misolar()));
drop policy if exists misolar_backend_automation_insert on public.automation_rules;
create policy misolar_backend_automation_insert on public.automation_rules for insert to anon
with check ((select private.request_is_misolar()));
drop policy if exists misolar_backend_automation_update on public.automation_rules;
create policy misolar_backend_automation_update on public.automation_rules for update to anon
using ((select private.request_is_misolar())) with check ((select private.request_is_misolar()));

drop policy if exists misolar_backend_configuration_events_select on public.inverter_configuration_events;
create policy misolar_backend_configuration_events_select on public.inverter_configuration_events for select to anon
using ((select private.request_is_misolar()));
drop policy if exists misolar_backend_configuration_events_insert on public.inverter_configuration_events;
create policy misolar_backend_configuration_events_insert on public.inverter_configuration_events for insert to anon
with check ((select private.request_is_misolar()));

comment on table public.automation_rules is 'Preferencia persistente de programación por inversor; modo manual hasta validar la ejecución autónoma.';
comment on table public.inverter_configuration_events is 'Auditoría inmutable de lecturas y cambios de Redischarge y Output.';
